### ISSUE TITLE
Packages for the upcoming release of debian 'stretch' as new stable 

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#10]
Hi,

I don't know if I am right here with my issue.

The release of Debian 'Stretch' as new stable branch is [announced for the 2017-06-17](https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html).

Will there be packages on packages.icinga.com for the new release?

**Comment by lazyfrosch** [comment]
Will take care of this next week ;)

**Comment by mcktr** [comment]
Thanks :)

**Comment by lazyfrosch** [comment]
Packages for Debian stretch has been published.

We would appreciate feedback :wink:
