### ISSUE TITLE
Implement rsync from <something>.icinga.com to enable creation of local repos

### ISSUE THREAD

**Issue by Ozzard** [Icinga/icinga-packaging#101]
This isn't quite a packaging request, but I'm not sure where else to ask - very happy to be given a pointer to a better location and for this issue to be closed.

I manage a bunch of machines that are used for clinical research and related purposes.  As you can imagine, they're quite thoroughly locked down, and they don't have general Internet access.  We've got reasonably automated acquisition of updates from other repositories via rsync onto our test network, but I can't find a rsync server for the Icinga packages (under /epel, in case it matters).

It'd be lovely to have rsync from <something>.icinga.com rather than having to scrape the web site.  Does this exist / is this the right place to ask / should I ask elsewhere / is this never going to happen?

Thanks for any information!

**Comment by lazyfrosch** [comment]
This is enabled for a long time:

```
$ rsync packages.icinga.com::packages
drwxrwxr-x          4,096 2018/05/22 14:45:43 .
-rw-rw-r--            419 2017/05/29 14:20:14 HEADER.html
-rw-r--r--            653 2017/11/17 13:15:27 Makefile
-rw-r--r--         10,151 2018/03/26 23:46:17 README.html
-rw-r--r--          5,612 2018/04/24 14:15:16 README.md
-rw-rw-r--            451 2016/07/12 11:07:04 favicon.ico
-rw-rw-r--          1,723 2016/07/12 11:07:03 icinga.key
drwxrwxr-x          4,096 2017/11/17 14:16:59 SUSE
drwxrwxr-x          4,096 2017/12/09 22:28:01 debian
drwxrwxr-x          4,096 2018/03/26 15:59:42 epel
drwxrwxr-x          4,096 2018/05/02 13:03:01 fedora
drwxrwxr-x          4,096 2017/11/17 14:18:30 openSUSE
drwxrwxr-x          4,096 2017/11/17 13:16:25 res
drwxrwxr-x          4,096 2018/03/26 15:59:42 ubuntu
drwxr-xr-x          4,096 2018/05/29 09:08:01 windows
```

I also suggest reposync or aptly to local mirrors.
