### ISSUE TITLE
Broken Icinga2 SLES12SP3 and SLES11SP4 repository (again)

### ISSUE THREAD

**Issue by thomas-merz** [Icinga/icinga-packaging#102]
The metadata (repodata) of https://packages.icinga.org/SUSE/12.3/release/ seems not to be in sync with the content of the repository. This is the error I get if I try to mirror it with Suse Manager (SMT):

2018/04/29 23:30:09 +02:00 Importing packages started.
2018/04/29 23:30:18 +02:00 Importing packages finished.
2018/04/29 23:30:18 +02:00 Linking packages to channel.
2018/04/29 23:30:20 +02:00 Repo https://packages.icinga.org/SUSE/12.3/release/ has 0 patches.
2018/04/29 23:30:20 +02:00 Sync completed.
2018/05/06 23:30:00 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'icinga2-sles12-sp3', '--type', 'yum', '--non-interactive']
2018/05/06 23:30:00 +02:00 Sync of channel started.
2018/05/06 23:30:01 +02:00 Retrieving 'repodata/ea64bf5bef9d837c6e038a525cb6467af0d9a189-primary.sqlite.bz2' failed: File not found in repository 'icinga2-sle12-sp3'
2018/05/13 23:30:00 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'icinga2-sles12-sp3', '--type', 'yum', '--non-interactive']
2018/05/13 23:30:00 +02:00 Sync of channel started.
2018/05/13 23:30:00 +02:00 Retrieving 'repodata/ea64bf5bef9d837c6e038a525cb6467af0d9a189-primary.sqlite.bz2' failed: File not found in repository 'icinga2-sle12-sp3'

The same for SLES11SP4:

2018/04/28 21:30:15 +02:00 Importing packages started.
2018/04/28 21:30:19 +02:00 Importing packages finished.
2018/04/28 21:30:19 +02:00 Linking packages to channel.
2018/04/28 21:30:21 +02:00 Repo https://packages.icinga.org/SUSE/sles11-sp4/release/ has 0 patches.
2018/04/28 21:30:21 +02:00 Sync completed.
2018/05/05 21:30:00 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'icinga2-sles11-sp4', '--type', 'yum', '--non-interactive']
2018/05/05 21:30:00 +02:00 Sync of channel started.
2018/05/05 21:30:01 +02:00 Retrieving 'repodata/6aa790f93d2a0c34b79186fd6cd93e0e60b12b93-primary.sqlite.bz2' failed: File not found in repository 'icinga2-sles11-sp4'
2018/05/12 21:30:00 +02:00 Command: ['/usr/bin/spacewalk-repo-sync', '--channel', 'icinga2-sles11-sp4', '--type', 'yum', '--non-interactive']
2018/05/12 21:30:00 +02:00 Sync of channel started.
2018/05/12 21:30:01 +02:00 Retrieving 'repodata/6aa790f93d2a0c34b79186fd6cd93e0e60b12b93-primary.sqlite.bz2' failed: File not found in repository 'icinga2-sles11-sp4'

**Comment by dnsmichi** [comment]
That sounds more like a stale cache on your end. Are you behind an HTTP proxy maybe?

**Comment by thomas-merz** [comment]
Yes, unfortunaly SUSE Manager is behind a HTTP(S) proxy. I will ask our proxy-team and give feedback here.

**Comment by thomas-merz** [comment]
Hi @dnsmichi , you have been right:
This problem was related to proxy caching (which is now off for this domain).
