### ISSUE TITLE
libmysql15 and sles 11.4

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga-packaging#107]
[Recent snapshot builds](https://build.icinga.com/job/icinga2-snapshot/job/rpm-sles-11.4-1binary/arch=x86_64/216/consoleFull) on this distro come with the following warning when installing the build dependencies:
```
The following packages need additional customer contract to get support:
  libecpg6 libmysqlclient15 libmysqlclient_r15 libpq5 
```

There is also a user [mentioning this dependency can not be satisfied](https://monitoring-portal.org/t/icinga2-ido-mysql-installation-problem/3250)

This is foremost a reminder ticket, this may or may not be something we need or can fix

**Comment by dnsmichi** [comment]
The forum URL is a different thing, the user has taken an external repository or RPM and altered the local installation to use libmysqlclient18 and MySQL 5.6. This remains an unsupported scenario by both, Icinga and SuSE. 

In terms of the warning, this is just a sanity check when upgrading packages. SuSE recently has split up specific packages into support groups (databases, web, etc.) for 12, and it seems, the same applies for 11 SP4 as well.

ftp://ftp.uni-halle.de/suse/SLES.11/SLES11-SP4/docu/RELEASE-NOTES.en.html#Support.Software

We don't need any support on such when building. If customers require SuSE's support to help with specific software problems on libmysqlclient, they'll need a specific support contract.

**Comment by Crunsher** [comment]
Aye, I misunderstood the issue and the warning.

Closed as not a bug.
