### ISSUE TITLE
Missing packages for OpenSUSE 15.0

### ISSUE THREAD

**Issue by wvdraay** [Icinga/icinga-packaging#110]
The icinga2 distributed with OpenSUSE 15.0 is horribly broken, so I'd love to run icinga2 from your repositories. But you are currently missing a 15.0 branch (and the 42.3 branch which I tried, is not compatible with 15.0). When do you expect to have a 15.0 branch ready?

**Comment by jsaathof** [comment]
+1 Packages for openSUSE 42.3 complain about a specific version of libboost-atomic when trying to install on openSUSE 15.

> Problem: nothing provides libboost_atomic.so.1.54.0()(64bit) needed by icinga2-bin-2.9.1-1.icinga.x86_64
 Solution 1: do not install icinga2-2.9.1-1.icinga.x86_64
 Solution 2: break icinga2-bin-2.9.1-1.icinga.x86_64 by ignoring some of its dependencies

OpenSUSE 15 has been out for some time now. Please create the packages and a repo for openSUSE 15.

**Comment by lazyfrosch** [comment]
Work is in progress

**Comment by dnsmichi** [comment]
Recent Icinga 2 releases have been published for OpenSUSE 15.

http://packages.icinga.com/openSUSE/15.0/

**Comment by lazyfrosch** [comment]
![good news everone](https://user-images.githubusercontent.com/121874/47798308-6bb11d80-dd28-11e8-819c-fe65854f2910.jpg)

Packages for SLES 15 has been released!

https://packages.icinga.com/SUSE/

Also snapshot builds are now active.
