### ISSUE TITLE
icinga2-2.9.1 failed to build for armhf

### ISSUE THREAD

**Issue by StHartwig** [Icinga/icinga-packaging#112]
Hello,

I have build the icinga2 - Package for raspi pi 3 on armhf7. The build of the version 2.9.1 from git, deb-package from packages.icinga.com and the icinga-stretch-snapshots failed. The build ist sucessfully, but all tests failed. See the log of sbuild attached.

When I add "-DICINGA2_WITH_TESTS=false \" in the git-repro (checkout 2.9.1) for icinga2 and deb-icinga2 the file "debian/rules", then the build is sucessfully. But when I will install these on my raspberry, then the binary (icinga2) failed with an "segmention fault".

My package build with the icinga2 2.8.4-1 from the deb-package form packages.icinga.com successfull and work sucessfull on my raspi with raspian (Stretch).

[icinga2_2.9.1+189.geee4426dc.2018.09.18+1.stretch-0_armhf-2018-09-23T12:13:08Z.build.txt](https://github.com/Icinga/icinga-packaging/files/2408769/icinga2_2.9.1%2B189.geee4426dc.2018.09.18%2B1.stretch-0_armhf-2018-09-23T12.13.08Z.build.txt)

Please have a look in the development version, and maybe fixed that for the next build version.

**Comment by lazyfrosch** [comment]
This looks more like a cross-building issue. It is normal that you can not run tests from a armhf binary on amd64.

Currently we have no resources publishing armhf packages, see #20
