### ISSUE TITLE
icinga2: Can't send external Icinga command to the local command file "/var/run/icinga2/cmd/icinga2.cmd": Permission denied.

### ISSUE THREAD

**Issue by karthikvrsjp** [Icinga/icinga-packaging#113]
I have seen this issue being posted by a couple of others and tried the resolution suggested but in vain. I get a warning and I want to acknowledge it. Got this error. 

Can you please suggest resolutions? Thanks in advance.

**Comment by karthikvrsjp** [comment]
![2018-10-02 00_02_26-icinga web](https://user-images.githubusercontent.com/32120731/46308138-816ede00-c5d6-11e8-81f3-2515973ebef5.jpg)

**Comment by karthikvrsjp** [comment]
![2018-10-02 00_03_21-icinga web](https://user-images.githubusercontent.com/32120731/46308194-a9f6d800-c5d6-11e8-844b-67f265ef21d7.jpg)

**Comment by lazyfrosch** [comment]
This issue is very broad.

You would normally need to enable the [command feature](https://www.icinga.com/docs/icinga2/latest/doc/14-features/#external-commands)

Default permissions should be fine, maybe you should validate them and post **details** here.

We don't even know your OS...

**Comment by dnsmichi** [comment]
That's the wrong tracker. Try the community channels prior to opening an issue on GitHub.

**Comment by lazyfrosch** [comment]
Please see https://www.icinga.com/community

You can always come back when there is a reproducible issue...
