### ISSUE TITLE
Change Debian package suffixes for release upgrades

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-packaging#120]
Currently all package versions end in `-1.<dist>`, so:

```
x.x.x-1.trusty
x.x.x-1.xenial
x.x.x-1.stretch
```

This came apparent with latest Ubuntu releases, where Canonical rolled over the codenames alphabetically. Currently the OS won't upgrade `2.10.1-1.xenial` to `2.10.1-1.bionic` to to alphabetical order.

To have proper version information we should switch over to numeric version suffixes, this will guarantee that Icinga 2 packages will be upgraded.

Examples:

```
x.x.x-1.ubuntu1604
x.x.x-1.ubuntu1804
x.x.x-1.debian9
x.x.x-1.debian10
```

Question: Is `debian10` newer than `debian9`?

/cc @R-Sommer

**Comment by lazyfrosch** [comment]
Yes it works:

```
$ dpkg --compare-versions 1.1.1-1.debian10 gt 1.1.1-1.debian9; echo $?
0
```

**Comment by lazyfrosch** [comment]
This is still pending, you should be able to fully upgrade like this:

```
sudo apt-get install icinga2 --allow-downgrades
```

**Comment by r4a5a88** [comment]
I tried it today and got this
`icinga2 ist schon die neueste Version (2.10.5-1.stretch).`
icinga2 is on the newest version

**Comment by ThreeFx** [comment]
Is there an ETA  on changing the versioning? We are currently suffering from the same issue.

**Comment by dnsmichi** [comment]
This will hopefully solve itself when I release 2.11 today.

**Comment by waja** [comment]
Unfortunately this did not fix this issue. Actually I'm working around something like this:
```
ICINGA2_VER="$(apt-cache policy icinga2| grep "\.buster" | head -1 | awk '{print $1}')" && [ -n "${ICINGA2_VER}" ] && apt install icinga2-bin=${ICINGAWEB2_VER} icinga2-common=${ICINGAWEB2_VER}
```
Same goes for `icingaweb2`. But this isn't a no brainer like moving away from release names in package versions but using distibutions release versions like "~deb10" and "~deb9" or something like this.

**Comment by Kazyini** [comment]
Any news?

**Comment by Al2Klimov** [comment]
This has been fixed for new packages: https://packages.icinga.com/debian/pool/main/i/icinga-kubernetes/
