### ISSUE TITLE
Error installing icinga2 on RHEL7

### ISSUE THREAD

**Issue by tzimmermanFSU** [Icinga/icinga-packaging#122]
I'm running RHEL 7.6 for now on a test VM in VirtualBox.
I ran this command to add the icinga repo to my VM:
yum install https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm

When I try to run the "yum install icinga2" command I'm getting the following error:
http://packages.icinga.com/epel/7.6-4.el7/release/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by lazyfrosch** [comment]
That's strange, we are just using the common `$releasever`, which should be `7Server` in your case.

```
$ cat /etc/yum.repos.d/ICINGA-release.repo 
[icinga-stable-release]
name=ICINGA (stable release for epel)
baseurl=http://packages.icinga.com/epel/$releasever/release/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ICINGA
```

I tried with RedHat's Docker image, and it seems to be the same behavior...

https://asciinema.org/a/CpLWp5JXKapytcJejeGDBaU8P

Not sure what is wrong here, I have the same release RPM in my Docker image: `redhat-release-server-7.6-4.el7.x86_64`

Maybe you should ask RedHat support what's happened with `$releasever` here. [Documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sec-configuring_yum_and_yum_repositories#sec-Using_Yum_Variables)

**Comment by lazyfrosch** [comment]
Of course you can always replace `$releasever` by `7` or `7Server`
