### ISSUE TITLE
EPEL package only with mayor versions

### ISSUE THREAD

**Issue by julenl** [Icinga/icinga-packaging#123]
To the best of my knowledge, we are supposed to install the EPEL packages like this:

    yum -y install https://packages.icinga.com/epel/icinga-rpm-release-${FIGURE_OUT_YOURSELF}-latest.noarch.rpm

Which installs a two repos with lines like:

    baseurl=http://packages.icinga.com/epel/$releasever/release

I see two problems here:

1. Why not to make a meta package which checks the current version and decides which repo to install? ... instead of guessing the $FIGURE_OUT_YOURSELF variable?

2. Given that the repos only support mayor release versions, the "$releasever" string on the baseurl definition, if we use a (OK... no supported) distro like Scientific Linux 6.5, the "$releasever" on the repo URL gets translated as

    https://packages.icinga.com/epel/6.5/release

A lot of symbolic links on the server could do the (dirty) job, but maybe better to let the package round up that number for us and set it as a string. Don't you think?

If anyone has the knowledge to decide that they want to use the release version 7 on a CentOS 6.5, they probably don't need a package to drop a few lines in two files anyway...

**Comment by dnsmichi** [comment]
I'm always navigating to http://packages.icinga.com/epel/ and copy the URL to the release RPM for 7. Which itself links to the latest package revision in the background, http://packages.icinga.com/epel/7/release/noarch/

It seems that someone or something changed the way how the `$releasever` macro works. Typically this translates to `7` in my systems on CentOS, I never had a problem with that.

Suppose you're using Scientific Linux, why is that different there?

> If anyone has the knowledge to decide that they want to use the release version 7 on a CentOS 6.5, they probably don't need a package to drop a few lines in two files anyway...

You can also use Puppet's yumrepo module and build that yourself, that's true. Having such in a package is more convenient imho. That's why I've created this many years ago following the EPEL idea.

**Comment by julenl** [comment]
Thanks @dnsmichi, hmm... in that case, the clean solution would be to find out why is that `$releasevers` not parsed properly...
And you are right, it also translates to me properly in CentOS.
Could that be an Scientific Linux bug? ... in where? yum?

About the puppet thing, sure. Well... In this precise case I am using ansible, but sure it can be done.
I am trying to build a whole user friendly, fool&bullet-proof icinga2/director management system, and I just want to save as much as I can in non necessary tasks.
If I can install the whole thing with a single (or two) yum/apt commands, it's way better than having to discover, install, hack, fix, install more, ... 

Which option would you prefer in your code:
 
    yum -y install epel-release https://packages.icinga.com/epel/icinga.repo
    yum -y install icinga2

or

    my_release=$(cat /etc/os-release | grep ... | awk ... | cut -d'.' ... )
    yum -y install epel-release https://packages.icinga.com/epel/icinga-longstring-${my_release}-stuff.noarch.repo
    sed -i '/baseurl/ s/... /' /etc/yum.repos.d/ICINGA-....repo
    yum -y install icinga2

With the second approach, there will be definitely hosts that will fail. Also, it hurts in the eyes to look at it.

**Comment by julenl** [comment]
Thanks @lazyfrosch. Sure, but maybe there could be a meta package like "icinga-rpm-release-latest.noarch.rpm" which parses the current release version and sets the repository address accordingly.
That sounds kind of trivial to implement...

If not possible/wanted, let's let the configuration manager handle the issue.

**Comment by dnsmichi** [comment]
> With the second approach, there will be definitely hosts that will fail. Also, it hurts in the eyes to look at it.

Just curious, since I am not an Ansible user ... aren't there any sort system facts one can access, like `operatingsystemmajrelease` with Puppet?

**Comment by lazyfrosch** [comment]
@julenl I get your point, but still I don't think many other vendors do this, and I don't have to have a meta package that installs another meta package. You need to know what OS you are on, and which major version it is.

@dnsmichi sure `ansible_distribution_major_version`

**Comment by julenl** [comment]
@dnsmichi , @lazyfrosch: Thanks!
Well... fair enough.
By the way, isn't that what the "epel-release" package does? 
...and, why not to put the stable packages directly in EPEL?

**Comment by lazyfrosch** [comment]
@julenl EPEL Release is also split in a version for `6` and `7`

I guess what we do will adapt is not using `$releasever` in the repo files anymore.

Uploading to EPEL is really complicated and we are not involved in the project. Our own repositories is the only reliable way to ship updates asap.

**Comment by lazyfrosch** [comment]
Lets continue with #123 - will take care of this soonish
