### ISSUE TITLE
Avoid releasever in our repo files

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-packaging#124]
`$releasever` should not be used, at least with the release RPMs.

Some distributions ship weird defaults here, examples:

* `7Server`
* `7Client`
* `6.5`

refs #123

**Comment by Al2Klimov** [comment]
The first ones you mentioned are already handled via symlinks. AL 2023 even uses three version digits, so I've added a RewriteRule in https://github.com/Icinga/packages.icinga.com/pull/40. I opt pro releasever.
