### ISSUE TITLE
Provide Ubuntu Cosmic (18.10) packages

### ISSUE THREAD

**Issue by andreasscherbaum** [Icinga/icinga-packaging#125]
As of now, the latest supported Ubuntu version is Cosmic. No packages for Cosmic are available in the repository:

http://packages.icinga.com/ubuntu/

Cosmic (18.10) is a released Ubuntu version.

**Comment by lazyfrosch** [comment]
Builds have been published: http://packages.icinga.com/ubuntu/dists/icinga-cosmic/
