### ISSUE TITLE
SLES 11 SP4 EOL: 31.3.2019

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#127]
https://www.suse.com/lifecycle/

- [x] Build containers & jobs
- [x] Docs (Icinga 2)

**Comment by lazyfrosch** [comment]
Jobs have already been disabled from the build system

@dnsmichi updated Icinga 2 docs (2.11)

I just updated the [support details on icinga.com](https://icinga.com/support/support-details/)
