### ISSUE TITLE
missing libboost for sles 12

### ISSUE THREAD

**Issue by n0braist** [Icinga/icinga-packaging#136]
package libboost_chrono1_69_0-icinga-1.69.0-2.icinga.x86_64.rpm  in repository, but libboost_chrono.so.1.54.0()(64bit) is missing

message
Problem: nothing provides libboost_chrono.so.1.54.0()(64bit) needed by icinga2-bin-2.10.5-1.icinga.x86_64

chrono1 is installed
zypper search libboost_chrono                           
S  | Name                               | Summary                                      | Type   
---+------------------------------------+----------------------------------------------+--------
i+ | libboost_chrono1_69_0-icinga       | The Boost::Chrono runtime library            | package
i+ | libboost_chrono1_69_0-icinga-devel | Development headers for Boost.Chrono library | package

**Comment by dnsmichi** [comment]
libboost*-icinga are packages required by the upcoming 2.11 release. For 2.10.5, you'll need the `SLES 12 SDK` repository.

**Comment by lazyfrosch** [comment]
It is included in `SLE-SDK12-SP4-Updates` by SUSE, we have no idea why a library is shipped with SDK.

Icinga 2.11 will switch to our own build for Boost.
