### ISSUE TITLE
Debian buster snapshot packages are outdated 

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#137]
Currently I am testing the snapshot packages, during that I noticed that the snapshot packages on Debian buster are outdated. 

Snapshot versions:

Debian buster:
```
root@deb10-icinga2-master:/# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.5-873-g56a5964c1)
```

Debian stretch:
```
root@deb9-icinga2-master:/# icinga2 -V
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.5-895-g7c10b9a0d)
```

Notice the version difference `-873-g56a5964c1` on buster and `-895-g7c10b9a0d` on stretch.

**Comment by lazyfrosch** [comment]
We migrated builds to GitLab recently. Also some unit tests have caused problem.

Should be fixed now as we prepare for 2.11
