### ISSUE TITLE
Builds for Icinga 2 v2.11 RC and Icinga Web 2 v2.7.0 are missing for Debian jessie

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#140]
I noticed that the packages for current Icinga 2 v2.11 RC1 and Icinga Web 2 v2.7.0 are missing for Debian jessie. As far as I know Debian jessie was not eol'd in Icinga 2 v2.11 RC1 nor in Icinga Web 2 v2.7.0.

**Comment by lazyfrosch** [comment]
Debian jessie has been EOL'd, it is even out of LTS now, we usually stop support when this happens.

We will not release newer packages for Debian jessie.

**Comment by mcktr** [comment]
According to the LTS wiki Debian jessie is still covered by LTS until June 2020.

https://wiki.debian.org/LTS

**Comment by lazyfrosch** [comment]
Oh you are right! :scream:

**Comment by dnsmichi** [comment]
2020 is when Jessie and el6 are EOL. Their OpenSSL versions (1.0.1) block several features in Icinga 2.

**Comment by lazyfrosch** [comment]
Sorry for the misunderstanding...

* Icinga 2.11 rc1 build for jessie is running: https://git.icinga.com/packaging/deb-icinga2/pipelines/4500
* Icinga Web 2.7 for jessie will be uploaded with 2.7.1 next week

If there is anything missing please let us know :wink: 

Now :tropical_drink: :palm_tree:
