### ISSUE TITLE
ubuntu - unable to install snapshots/testing in 16.04 and 18.04

### ISSUE THREAD

**Issue by maximo1610** [Icinga/icinga-packaging#142]
## Describe the bug
I am unable to install icinga2 using the bionic-snapshots repository due to dependency issues.

## To Reproduce
1. Install Ubuntu Server 18.04 LTS from cd and provide IP
2. Add Icinga2 repository following documentation from here (https://icinga.com/docs/icinga2/snapshot/doc/02-installation/) using the ubuntu method
3. Modify bionic-icinga.list to include '-snapshots' as I want to test 2.11
4. apt update && apt install icinga2

## Expected behavior
I would expect all dependencies to be met and the installation to complete.

## Output

```
apt install icinga2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0+rc1.8.ga9d5fe431.20190730.1543+bionic-0) but it is not going to be installed
           Recommends: libreadline6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

## Your Environment
bionic-icinga.list
```deb https://packages.icinga.com/ubuntu icinga-bionic-snapshots main```

## Additional context
libreadline6 is not available in the ubuntu repositories for bionic according to: https://packages.ubuntu.com/search?keywords=libreadline6
But aside from that it will not install icinga2-bin

**Comment by dgoetz** [comment]
Adding information from @sounddudenz out of https://github.com/Icinga/icinga2/issues/7426

Looks like libreadline6 has deleted and libreadline7 is now used.

Someone will need to update the dependices for the Bionic packages and rebuild

libreadline6 is no longer in universe or backports :-(

**Comment by dnsmichi** [comment]
Agreed on the package renaming, but the installation succeeds here in Docker. `libreadline6` is a suggested package, not a required one. It helps with keeping the debug console history, nothing else you would need in prod.

https://icinga.com/docs/icinga2/snapshot/doc/21-development/#ubuntu - just tested this.

**Comment by dnsmichi** [comment]
The newer snapshot packages are not published correctly by aptly btw, this is already tracked at https://rt.icinga.com/Ticket/Display.html?id=16621

**Comment by maximo1610** [comment]
> Agreed on the package renaming, but the installation succeeds here in Docker. `libreadline6` is a suggested package, not a required one. It helps with keeping the debug console history, nothing else you would need in prod.
> 
> https://icinga.com/docs/icinga2/snapshot/doc/21-development/#ubuntu - just tested this.

I have tested this and can confirm it is working.

**Comment by lazyfrosch** [comment]
libreadline8 and 7 will be added as recommended. This is unfortunately not automatic, since it is an optional dependency.

The initial issue here was something different. @maximo1610 what did fix your issue?
