### ISSUE TITLE
Icinga Web Modules for Debian Buster (10)

### ISSUE THREAD

**Issue by jamiek23** [Icinga/icinga-packaging#143]
As Debian Buster is now being pushed as [stable](https://www.debian.org/News/2019/20190706), it would be nice if the four Icinga Web Modules currently packaged could be rebuilt for Buster. Currently they are only available for Jessie and Stretch.

Looking at the packages themselves I suspect only the dpkg metadata will need updating. The stretch packages continue to work just fine after an upgrade!

#135 fixed this previously for most other packages, but the web modules don't appear to have been updated.

**Comment by lazyfrosch** [comment]
We are working on this, please follow our blog for a soonish announcement.

Also README lists the new packages now.
