### ISSUE TITLE
Some servers cannot connect to packages.icinga.com

### ISSUE THREAD

**Issue by ronneke1996** [Icinga/icinga-packaging#145]
Some of my servers cannot `curl -sSL https://packages.icinga.com/icinga.key | /usr/bin/apt-key add`, because they get a connection refused error.

I've added an MTR report.

![Screenshot from 2019-08-29 12-08-02aaaa](https://user-images.githubusercontent.com/9202089/64016904-7c891600-cb28-11e9-9ae6-fe15934df2c1.png)

**Comment by b0e** [comment]
Hi,

With which source IP are you trying to connect from? Due to some DDoS attacks in the recent weeks, we had to block some subnets. Your IP address is probably affected.

Regards,
b0e

**Comment by b0e** [comment]
Please write a DM or leave the information [here](https://icinga.com/contact/)

**Comment by lazyfrosch** [comment]
If this problem is still existing, please contact info@icinga.com

**Comment by mark-whc** [comment]
It's a brand new server. It's not on any RBL.
