### ISSUE TITLE
[~BUG] icinga2 Version 2.11.0-1.stretch Debian

### ISSUE THREAD

**Issue by mklooss** [Icinga/icinga-packaging#146]
The Debian Version icinga2 needs the libreadline6, but there is only "libreadline7"

```
apt-get install icinga2=2.11.0-1.stretch
[...]
The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0-1.stretch) but it is not going to be installed
           Recommends: libreadline6 but it is not installable
```

**Comment by mklooss** [comment]
Content from debian/control of the source package

`Package: icinga2
Architecture: any
Depends: icinga2-bin (= ${binary:Version}),
         icinga2-common (= ${source:Version}),
         ${misc:Depends}
Recommends: icinga2-doc (= ${binary:Version}), monitoring-plugins-basic | nagios-plugins-basic, libreadline6`

**Comment by dnsmichi** [comment]
Backports repository is enabled?

**Comment by dnsmichi** [comment]
I've triggered builts with -2 as revision which incorporates missing fixes for libreadline. You might want to run `apt-get update && apt-y install icinga2` once again.

**Comment by mklooss** [comment]
thanks :)
