### ISSUE TITLE
Debian Stretch AMD64 - unmet dependencies

### ISSUE THREAD

**Issue by tkoeck** [Icinga/icinga-packaging#149]
sources.list file looks like that

deb http://packages.icinga.com/debian icinga-stretch main
deb-src http://packages.icinga.com/debian icinga-stretch main
~                                                             
root@git:/etc/apt/sources.list.d# apt-get install icinga2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0-2.stretch) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tkoeck** [comment]
Okay with the backport it works. Still not an elegant version.

**Comment by dnsmichi** [comment]
It is a better solution to use upstream available package sources than to create your own fork. Debian backports was exactly made for this, and I'm happy @lazyfrosch took care this way.

I can only recommend reading the upgrading docs closely.
 https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#added-boost-166

**Comment by tkoeck** [comment]
Yes backports work that way. The problem with backports is that security updates aren't deployed very fast. That means that the server are vulnerable for a longer period.

**Comment by dnsmichi** [comment]
From my knowledge you can control the package priorities with apt. Meaning to say, you only allow boost* from backports and disable everything else. That way you are safe in terms of security updates. 

Apart from this, building boost and maintaining it is not our primary focus with the many other tasks we have. Using the backports version allows us to minimize the distributions we really need to provide custom packages. Hopefully future distribution releases already provide Boost 1.66 without additional requirements.
