### ISSUE TITLE
Broken Install 2.11.0-2 Stretch

### ISSUE THREAD

**Issue by RamJett** [Icinga/icinga-packaging#150]
On running apt-get upgrade we get on ALL of out Debian 9 boxes

First "apt-get install icinga2"
The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.11.0-2.stretch) but it is not going to be installed

Then "apt-get install icinga2 icinga2-bin"

The following packages have unmet dependencies:
 icinga2-bin : Depends: libboost-context1.67.0 but it is not installable
               Depends: libboost-coroutine1.67.0 but it is not installable
               Depends: libboost-date-time1.67.0 but it is not installable
               Depends: libboost-filesystem1.67.0 but it is not installable
               Depends: libboost-program-options1.67.0 but it is not installable
               Depends: libboost-regex1.67.0 but it is not installable
               Depends: libboost-system1.67.0 but it is not installable
               Depends: libboost-thread1.67.0 but it is not installable

I see only libboost versions on Stretch are
1.62

**Comment by RamJett** [comment]
So after adding stretch-backports I now get this error

critical/config: Error: Could not load library 'libpgsql_shim.so.2.11.0': libpgsql_shim.so.2.11.0: cannot open shared object file: No such file or directory

**Comment by dnsmichi** [comment]
https://icinga.com/docs/icinga2/latest/doc/02-installation/#installing-the-ido-modules-for-postgresql
