### ISSUE TITLE
Installing Icinga2 updated version in RHEL 7.6 got dependencies issues

### ISSUE THREAD

**Issue by Delat0918** [Icinga/icinga-packaging#160]
Hi, 

I am installing Icinga2 on our RHEL server but unfortunately got some dependencies issues.

Here are the steps I made in installing Icinga2. I followed from the  web the installation procedure.
https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-install-icinga-2-on-centos-7-rhel-7.html

1. I installed the repo first:
[root@dkrdswppicingp99 ~]# curl --insecure --output icinga-rpm-release-7-latest.noarch.rpm https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4376  100  4376    0     0  19177      0 --:--:-- --:--:-- --:--:-- 19277

[root@dkrdswppicingp99 ~]# rpm -ivh icinga-rpm-release-7-latest.noarch.rpm
Preparing...                          ################################# [100%]
Updating / installing...
   1:icinga-rpm-release-7-2.el7.centos################################# [100%]

[root@dkrdswppicingp99 ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Skipping unreadable repository '/etc/yum.repos.d/svn_3rd-party-local_el7.repo'
Skipping unreadable repository '/etc/yum.repos.d/svn_localrepo_el7.repo'
icinga-stable-release                                                                                                                                                            | 2.9 kB  00:00:00
rhel-7-server-extras-rpms                                                                                                                                                        | 3.4 kB  00:00:00
rhel-7-server-optional-rpms                                                                                                                                                      | 3.2 kB  00:00:00
rhel-7-server-rpms                                                                                                                                                               | 3.5 kB  00:00:00
rhel-server-rhscl-7-rpms                                                                                                                                                         | 3.4 kB  00:00:00
(1/13): icinga-stable-release/7Server/primary_db                                                                                                                                 | 195 kB  00:00:00
(2/13): rhel-7-server-extras-rpms/x86_64/group                                                                                                                                   |  124 B  00:00:00
(3/13): rhel-7-server-optional-rpms/7Server/x86_64/group                                                                                                                         |  26 kB  00:00:00
(4/13): rhel-7-server-extras-rpms/x86_64/updateinfo                                                                                                                              | 212 kB  00:00:01
(5/13): rhel-7-server-extras-rpms/x86_64/primary_db                                                                                                                              | 571 kB  00:00:00
(6/13): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                                                                                                    | 2.5 MB  00:00:00
(7/13): rhel-7-server-rpms/7Server/x86_64/updateinfo                                                                                                                             | 3.4 MB  00:00:00
(8/13): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                                                                                                    | 8.3 MB  00:00:00
(9/13): rhel-7-server-rpms/7Server/x86_64/group                                                                                                                                  | 773 kB  00:00:00
(10/13): rhel-server-rhscl-7-rpms/7Server/x86_64/group                                                                                                                           |  124 B  00:00:00
(11/13): rhel-server-rhscl-7-rpms/7Server/x86_64/updateinfo                                                                                                                      | 1.0 MB  00:00:00
(12/13): rhel-server-rhscl-7-rpms/7Server/x86_64/primary_db                                                                                                                      | 5.4 MB  00:00:00
(13/13): rhel-7-server-rpms/7Server/x86_64/primary_db                                                                                                                            |  62 MB  00:00:01
repo id                                                                          repo name                                                                                                      status
foreman-plugins                                                                  Foreman plugins                                                                                                     338
icinga-stable-release/7Server                                                    ICINGA (stable release for epel)                                                                                 574+48
puppet-agent                                                                     'puppet-agent local repository el6'                                                                                  13
rhel-7-server-extras-rpms/x86_64                                                 Red Hat Enterprise Linux 7 Server - Extras (RPMs)                                                                 1,190
rhel-7-server-optional-rpms/7Server/x86_64                                       Red Hat Enterprise Linux 7 Server - Optional (RPMs)                                                            19,357+2
rhel-7-server-rpms/7Server/x86_64                                                Red Hat Enterprise Linux 7 Server (RPMs)                                                                         26,500
rhel-server-rhscl-7-rpms/7Server/x86_64                                          Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server                                          11,415
repolist: 59,387
[root@dkrdswppicingp99 ~]# yum search icinga2
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Skipping unreadable repository '/etc/yum.repos.d/svn_3rd-party-local_el7.repo'
Skipping unreadable repository '/etc/yum.repos.d/svn_localrepo_el7.repo'
======================================================================================== N/S matched: icinga2 =========================================================================================
icinga2-debuginfo.x86_64 : Debug information for package icinga2
icinga2-selinux.x86_64 : SELinux policy module supporting icinga2
nano-icinga2.x86_64 : Nano syntax highlighting for icinga2
vim-icinga2.x86_64 : Vim syntax highlighting for icinga2
icinga2.x86_64 : Network monitoring application
icinga2-bin.x86_64 : Icinga 2 binaries and libraries
icinga2-classicui-config.x86_64 : Icinga 2 Classic UI Standalone configuration
icinga2-common.x86_64 : Common Icinga 2 configuration
icinga2-doc.x86_64 : Documentation for Icinga 2
icinga2-ido-mysql.x86_64 : IDO MySQL database backend for Icinga 2
icinga2-ido-pgsql.x86_64 : IDO PostgreSQL database backend for Icinga 2
icinga2-libs.x86_64 : Libraries for Icinga 2

  Name and summary matches only, use "search all" for everything.

* I installed the icinga2 but dependecies issues were encountered.

[root@dkrdswppicingp99 ~]# yum install icinga2
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Skipping unreadable repository '/etc/yum.repos.d/svn_3rd-party-local_el7.repo'
Skipping unreadable repository '/etc/yum.repos.d/svn_localrepo_el7.repo'
Resolving Dependencies
--> Running transaction check
---> Package icinga2.x86_64 0:2.11.1-1.el7.icinga will be installed
--> Processing Dependency: icinga2-bin = 2.11.1-1.el7.icinga for package: icinga2-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: icinga2-common = 2.11.1-1.el7.icinga for package: icinga2-2.11.1-1.el7.icinga.x86_64
--> Running transaction check
---> Package icinga2-bin.x86_64 0:2.11.1-1.el7.icinga will be installed
--> Processing Dependency: libboost_program_options.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_date_time.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_thread.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_context.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_regex.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_coroutine.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_system.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
--> Processing Dependency: libboost_filesystem.so.1.69.0()(64bit) for package: icinga2-bin-2.11.1-1.el7.icinga.x86_64
---> Package icinga2-common.x86_64 0:2.11.1-1.el7.icinga will be installed
--> Finished Dependency Resolution
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_date_time.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_regex.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_context.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_thread.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_system.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_coroutine.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_program_options.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_filesystem.so.1.69.0()(64bit)
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_date_time.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_regex.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_context.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_thread.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_system.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_coroutine.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_program_options.so.1.69.0()(64bit)
Error: Package: icinga2-bin-2.11.1-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libboost_filesystem.so.1.69.0()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@dkrdswppicingp99 ~]# rpm -qa |grep icinga
icinga-rpm-release-7-2.el7.centos.noarch

**Comment by dnsmichi** [comment]
Blogs usually cannot catch up with the latest changes. Please always refer to the official documentation with installation and upgrading hints. In this regard, the EPEL repository is a hard dependency for 2.11: https://icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#added-boost-166

**Comment by Delat0918** [comment]
Hi, Michael.

Thanks for the detailed info. I have found out that I've missed the epel repo to install . This was resolve by that EPEL. Thanks again :)
