### ISSUE TITLE
Icingabeat missing in SLES 12.4 repository

### ISSUE THREAD

**Issue by XnS** [Icinga/icinga-packaging#161]
Hi,

icingabeat package is missing in SLES 12.4 repository [1]. For SLES 12.3 its still there [2]

[1] https://packages.icinga.com/SUSE/12.4/release/x86_64/
[2] https://packages.icinga.com/SUSE/12.3/release/x86_64/

Regards,
~X

**Comment by dnsmichi** [comment]
Icingabeat needs a new release and migration to GitLab CI jobs @bobapple. That'll be a task in the coming weeks.

**Comment by dnsmichi** [comment]
Since CI integration is not trivial with docker-in-docker & uploads, fallback to the GH releases works for now. I'm using that in Puppet for the Vagrant boxes as well.

**Comment by htriem** [comment]
Icingabeat should be available now for SLES 12.4.
