### ISSUE TITLE
Change default protocol from http to https in icinga-rpm-release & online docs

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icinga-packaging#162]
By accident I ran over the fact that our icinga2-release.rpm which is used to setup icinga2 repository are still deliviered with http protocol setting for packages.icinga.com connection.

This should be change to https by default.

Also it should be considered if we could do the same on Deb like system. Since deb don't use repo packages we perhaps could change the documentation on packages.icinga.com to https. So everyone who's lazy will use https by default in future. If we do this step dependency to apt-transport-https needs to be added as well.

Yes its just a small step in security and maybe not the overall solution but its a step forward.

Regards,
Max

**Comment by dnsmichi** [comment]
Affects icinga-rpm-release as well.

**Comment by lazyfrosch** [comment]
Forcing https is not a good idea as we should let the user decide this.

All documentation should use https, the release RPMs ship the GPG key internally.
