### ISSUE TITLE
SLES 12 SP5 support

### ISSUE THREAD

**Issue by lgraziosi** [Icinga/icinga-packaging#170]
SLES12 SP5 was released on Monday. It will be the last service pack for SLES 12.  
https://www.suse.com/c/suse-linux-enterprise-12-service-pack-5-is-generally-available/

Please consider building its RPMs. Thank you.

**Comment by Shazootua9sh** [comment]
The repository for SLES 12 SP 5  does not contain a metadata signature, like:
  https://packages.icinga.com/SUSE/12.5/release/repodata/repomd.xml.asc

Please consider adding a valid signature, and thanks for adding SLES 12 SP 5 support.

**Comment by dgoetz** [comment]
@htriem It is missing a `gpg --armor --detach-sign repodata/repodata.xml` somewhere to sign the metadata. Should be done for the SuSE family as it is required by zypper's default settings.

**Comment by htriem** [comment]
Hey :) 

The repository should contain the metadata signature now. Would anybody be willing to confirm?

**Comment by N-o-X** [comment]
Seems like everything is working. I'll close this issue. If anyone still has problems with those packages, please let us know.
