### ISSUE TITLE
repo for arm64 (pine64 with armbian)

### ISSUE THREAD

**Issue by PointPubMedia** [Icinga/icinga-packaging#172]
Hey guys....

Right now we are using more and more pine64 board instead of raspberry only for a storage issue.  pine64 board, like the rock64 and rockpro64 board are having a MMC storage that is more robust as SD Card for the rPI!

Is there any chance we can have a repo for arm64 architecture ?

We can help if you need something to make it...
Right now, we are having icinga2 from the distro, so we are working and functional but we would like to have a repo to be up to date!

**Comment by htriem** [comment]
Closed as a duplicate, we'll continue the discussion in #220.
