### ISSUE TITLE
icingadb package not available for 32-bit Ubuntu

### ISSUE THREAD

**Issue by riban-bw** [Icinga/icinga-packaging#176]
The [installation instructions](https://icinga.com/docs/icingadb/latest/doc/02-Installation/) for icingadb result in an error for Ubuntu:

    Unable to locate package icingadb

This is with Ubutnu 18.04.4 LTS 32-bit fresh install. The icinga-testing repository is added and authenticated.

icingadb is available in the [amd64 package list](https://packages.icinga.com/ubuntu/dists/icinga-bionic-testing/main/binary-amd64/Packages) but not in the [i386 package list](https://packages.icinga.com/ubuntu/dists/icinga-bionic-testing/main/binary-i386/Packages).

**Comment by htriem** [comment]
@N-o-X Is that something we still look for to support with IcingaDB?

**Comment by N-o-X** [comment]
Hi @riban-bw,

sorry for the late answer. Since Ubuntu and many other distributions dropped the support for 32 bit, we don't think it's something worth supporting any more.

Greetings,
Noah
