### ISSUE TITLE
Unable to install a specific version on debian and ubuntu

### ISSUE THREAD

**Issue by lbetz** [Icinga/icinga-packaging#177]
When I'd like to install an older version of icinga2 I get this:

#  apt-get install icinga2=2.10.7-1.buster
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2 : Depends: icinga2-bin (= 2.10.7-1.buster) but 2.11.3-1.buster is to be installed
           Depends: icinga2-common (= 2.10.7-1.buster) but 2.11.3-1.buster is to be installed
           Recommends: icinga2-doc (= 2.10.7-1.buster) but it is not going to be installed
           Recommends: monitoring-plugins-basic but it is not going to be installed or
                       nagios-plugins-basic
E: Unable to correct problems, you have held broken packages.

... and of course this version is available in my repositories:

#  apt-cache policy icinga2
icinga2:
  Installed: (none)
  Candidate: 2.11.3-1.buster
  Version table:
     2.11.3-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.11.2-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.11.1-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.11.0-2.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.11.0-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.10.7-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.10.5-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages
     2.10.4-1.buster 500
        500 http://packages.icinga.com/debian icinga-buster/main amd64 Packages

**Comment by dgoetz** [comment]
Perhaps the same problem you would have on RPM systems that you need to specify also the dependent packages with version?

**Comment by N-o-X** [comment]
I'm not sure, if that is a problem with our packages or an apt behaviour. This should work though (didn't test):
```
APT_VERSION=2.10.7-1.buster
apt-get install -y icinga2-bin=$APT_VERSION icinga2-common=$APT_VERSION icinga2=$APT_VERSION
```

**Comment by lbetz** [comment]
Of course I can but I won't. I'd like to use puppet

$ puppet resource package icinga2 ensure=2.10.7-1.buster

... and the rpms work fine
$ yum install icinga2-2.10.7-1.el7.icinga

**Comment by lazyfrosch** [comment]
Since downgrading is not really supported with APT, you will need to specify the version for each package separatly. @N-o-X is right, make sure to include any IDO package as well.

**Comment by lbetz** [comment]
No kidding! I wanna INSTALL this version not downgrade to.

**Comment by lazyfrosch** [comment]
APT is designed to work like this, it will always try to get the latest version, there is nothing we can do about it...

**Comment by N-o-X** [comment]
Wouldn't it be possible to just ensure the version of every Icinga package/dependency with Puppet?

**Comment by lazyfrosch** [comment]
You will to have to write a workaround for that I'm afraid. Most packages needing this behavior are only a single binary package...
