### ISSUE TITLE
Centos 8 & MariaDB

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icinga-packaging#179]
Hello,

for icinga-ido-mysql the linked libraries are hard to the mysql 8 server/client. There is no change to have icinga2 and the mariadb server on the same host because of package conflicts.

Will there be soon packages available that support mariadb too?

**Comment by lazyfrosch** [comment]
Sorry but linking against separate library doesn't make very much sense. It is the same protocol, only slightly different versions.

I don't see the actual problem in my test container, can you elaborate your problem a bit more? What source of packages are you using for MariaDB?

A Dockerfile and log here:
https://gist.github.com/lazyfrosch/263020864c88c0ec773cf56ae617db86

It should only install `mysql-libs` and `mysql-common`, which should not conflict with any package from MariaDB in Appstream

**Comment by whimpy** [comment]
The package mysql-common may not conflict with any MariaDB package in AppStream (haven't tried it) but it does conflict with the MariaDB-common package from the MariaDB repository:

`file /usr/share/mysql/charsets/Index.xml from install of mysql-common-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 conflicts with file from package MariaDB-common-10.5.5-1.el8.x86_64`
[etc for each file in /usr/share/mysql/charsets]

**Comment by whimpy** [comment]
The package mysql-common may not conflict with any MariaDB package in AppStream (haven't tried it) but it does conflict with the MariaDB-common package from the MariaDB repository:

`file /usr/share/mysql/charsets/Index.xml from install of mysql-common-8.0.17-3.module_el8.0.0+181+899d6349.x86_64 conflicts with file from package MariaDB-common-10.5.5-1.el8.x86_64`
[etc for each file in /usr/share/mysql/charsets]

**Comment by Al2Klimov** [comment]
IMAO the lack of external feedback for a long time indicates that that feedback will never happen. Therefore closing this one.

Feel free to re-open if the problem persists with the latest Icinga 2 version as long as you provide the desired information.
