### ISSUE TITLE
Debian APT connection issues

### ISSUE THREAD

**Issue by deric** [Icinga/icinga-packaging#180]
I'm having troubles with fetching packages list:
```
Err:7 http://packages.icinga.com/debian icinga-stretch InRelease                                                                                    
  Could not connect to packages.icinga.com:80 (185.11.254.87). - connect (111: Connection refused)
```
and obtaining packages as well:
```
Err:1 http://packages.icinga.com/debian icinga-stretch/main amd64 icinga2 amd64 2.11.3-1.stretch
  Could not connect to packages.icinga.com:80 (185.11.254.87). - connect (111: Connection refused)
Err:2 http://packages.icinga.com/debian icinga-stretch/main amd64 icinga2-bin amd64 2.11.3-1.stretch
  Unable to connect to packages.icinga.com:http:
Err:3 http://packages.icinga.com/debian icinga-stretch/main amd64 icinga2-common all 2.11.3-1.stretch
  Unable to connect to packages.icinga.com:http:
E: Failed to fetch http://packages.icinga.com/debian/pool/main/i/icinga2/icinga2_2.11.3-1.stretch_amd64.deb  Could not connect to packages.icinga.com:80 (185.11.254.87). - connect (111: Connection refused)
E: Failed to fetch http://packages.icinga.com/debian/pool/main/i/icinga2/icinga2-bin_2.11.3-1.stretch_amd64.deb  Unable to connect to packages.icinga.com:http:
E: Failed to fetch http://packages.icinga.com/debian/pool/main/i/icinga2/icinga2-common_2.11.3-1.stretch_all.deb  Unable to connect to packages.icinga.com:http:

```

**Comment by lazyfrosch** [comment]
Is it still unavailable? Could you share us your public ip address to info@icinga.com?

cc @bobapple

**Comment by deric** [comment]
Yes, it's still an issue. The problem might be with its location, the server is located in Australia.

There seems to be some packet loss on the way to Europe. I've tried to increase number of retries:
```
APT::Acquire::Retries "5";
```
but without any success.

**Comment by lazyfrosch** [comment]
This can be anything, beginning with DDOS prevention measure we had to to @NETWAYS

So IP and traceroute from your perspective would be helpful, or I can't help with your issue.

As alternative, there is a local mirror in New Zealand:
https://icinga.com/download/
https://mirror.fsmg.org.nz/icinga/

**Comment by bobapple** [comment]
I agree with @lazyfrosch 
We're having DDOS attacks from time to time and our hosting provider uses blackholing to prevent those. Best would be to get your details via email so we can check it!

**Comment by deric** [comment]
Thanks, I'll try the NZ mirror. I've tried sending an email to `info@icinga.com` but it bounced back:

```
Sender address rejected: Access denied (in reply
    to RCPT TO command)
```

**Comment by deric** [comment]
New Zeland mirror works fine, thanks!

**Comment by lazyfrosch** [comment]
Well, I should have thought of that... any DDOS prevention will cause problems here too.

Send your e-mail to markus@lazyfrosch.de or lazyfrosch@gmail.com

We want to find the problem :wink:

**Comment by lazyfrosch** [comment]
Follow Up: No connection issue from packages.icinga.com to be seen from our side.
