### ISSUE TITLE
[debian] Icinga Web 2 Package - apache 2 dependency

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icinga-packaging#183]
Hello,

is it possible to remove the apache2 dependency from icingaweb2 package and let the end user decide what type of webserver he want's to operate?

Also I would recommend to provide two packages:
- icingaweb2-apache2
- icingaweb2-nginx

At the moment it isn't really possible to install Icinga Web 2 out of the box on Debian 10 with nginx without breaking the whole dependency chain of icingaweb2 package.

Sincerly,

**Comment by lazyfrosch** [comment]
Debian should not need such split packages, we define alternatives here with `Recommends: apache2 | httpd`

https://git.icinga.com/packaging/deb-icingaweb2/-/blob/master/debian/control#L30

For whatever reason this does not work anymore, usually you only need to:

```
apt install nginx
apt install icingaweb2
```

I'm not sure why it is broken now...

**Comment by lazyfrosch** [comment]
nginx also provides this:

```
# apt show nginx-full
...
Provides: httpd, httpd-cgi, nginx
```

**Comment by lazyfrosch** [comment]
Asked debian-devel about this: https://lists.debian.org/debian-devel/2020/04/msg00136.html

**Comment by lazyfrosch** [comment]
The tiny bit I missed was PHP, and its ties with Apache. To avoid Apache you need to:

```
apt install nginx php-fpm
apt install icingaweb2
```

Recommends in question: `apache2 | httpd, php, ...`

`php` will install `php7.3`, which depends on: `libapache2-mod-php7.3 | php7.3-fpm | php7.3-cgi`
