### ISSUE TITLE
Can't install v2.12-rc1

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga-packaging#184]
## Describe the bug

... from our testing repo.

## To Reproduce

1. Same setup as Icinga/icinga2#7971 (Ubuntu 18.04)
2. `apt install icinga2-bin`

## Expected behavior

It installs.

## Screenshots

```
root@aklimov-7971-1:~# apt install icinga2-bin
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 icinga2-bin : Depends: libboost-coroutine1.67.0-icinga but it is not installable
               Depends: libboost-filesystem1.67.0-icinga but it is not installable
               Depends: libboost-program-options1.67.0-icinga but it is not installable
               Depends: libboost-regex1.67.0-icinga (>= 1.67.0-10) but it is not installable
               Depends: libboost-system1.67.0-icinga but it is not installable
               Depends: libboost-thread1.67.0-icinga but it is not installable
E: Unable to correct problems, you have held broken packages.
root@aklimov-7971-1:~#
```

**Comment by N-o-X** [comment]
Release boost packages for testing repository:

- [ ]  DEB
- [ ]  SUSE
- [ ]  RHEL
- [ ]  Raspbian

**Comment by lazyfrosch** [comment]
No, please don't - just enable testing and release repositories

**Comment by lazyfrosch** [comment]
Testing repos are to test packages, not include released packages, just bc the test packages need them

**Comment by lazyfrosch** [comment]
https://github.com/lazyfrosch/docker-icinga2/blob/52e48485231af7eaa61441fbbdc506458ac1acf8/Dockerfile#L8-L15

**Comment by Al2Klimov** [comment]
I agree with @N-o-X. As a user I shall not have to enable > 1 repo.

**Comment by lazyfrosch** [comment]
A user should use testing and snapshots only in rare cases. The boost packages are neither in a test, nor in a snapshot state, therefor they are only in the release repository.

Every user already has to do this when testing snapshots. That's why we took care of proper versioning between snapshot, test and release packages.

**Comment by Al2Klimov** [comment]
Then we shall at least update the copy&paste textblocks at https://packages.icinga.com/*, e.g.:

```
icinga-buster-testing i386 amd64

deb http://packages.icinga.com/debian icinga-buster main
deb-src http://packages.icinga.com/debian icinga-buster main
deb http://packages.icinga.com/debian icinga-buster-testing main
deb-src http://packages.icinga.com/debian icinga-buster-testing main
```

**Comment by Al2Klimov** [comment]
@N-o-X Shall we just close this as new Distros don’t require self-built Boost and old ones get dropped?

**Comment by htriem** [comment]
I'd agree with what @Al2Klimov is proposing.

**Comment by N-o-X** [comment]
👍
