### ISSUE TITLE
sles 11 sp4 nothing provides libcrypto .so.1.0.0

### ISSUE THREAD

**Issue by drumclimber** [Icinga/icinga-packaging#19]
Trying to install icinga2 on a fully patched sles 11 sp4 and recieve the following:

serverx:/home/icinga # zypper in -d icinga2
Loading repository data...
Reading installed packages...
Resolving package dependencies...

**Problem: nothing provides libcrypto.so.1.0.0 needed by icinga2-bin-2.6.3-1.i586**
 Solution 1: do not install icinga2-2.6.3-1.i586
 Solution 2: break icinga2-bin-2.6.3-1.i586 by ignoring some of its dependencies

or

serverx:/home/icinga # rpm -ivh icinga2-2.4.10-1.i586.rpm icinga2-bin-2.4.10-1.i586.rpm 
warning: icinga2-2.4.10-1.i586.rpm: Header V3 DSA signature: NOKEY, key ID 34410682
error: Failed dependencies:
        icinga2-common = 2.4.10-1 is needed by icinga2-bin-2.4.10-1.i586
        libboost_program_options.so.1.53.0 is needed by icinga2-bin-2.4.10-1.i586
        libboost_regex.so.1.53.0 is needed by icinga2-bin-2.4.10-1.i586
        libboost_system.so.1.53.0 is needed by icinga2-bin-2.4.10-1.i586
        libboost_thread.so.1.53.0 is needed by icinga2-bin-2.4.10-1.i586
        libcrypto.so.1.0.0 is needed by icinga2-bin-2.4.10-1.i586
        libedit.so.0 is needed by icinga2-bin-2.4.10-1.i586
        **libssl.so.1.0.0 is needed by icinga2-bin-2.4.10-1.i586**

**Comment by drumclimber** [comment]
disregard this found duplicate posts

**Comment by lazyfrosch** [comment]
Also see https://github.com/Icinga/icinga2/blob/55a057c606a67bae90898d07c9b0511315983321/doc/2-getting-started.md#-sles-security-repository

**Comment by drumclimber** [comment]
Thank you! I got it going. As stated in the docs you must have the security repository added as well as the icinga2 in order to install.
