### ISSUE TITLE
RHEL 8 Apache/PHP-FPM

### ISSUE THREAD

**Issue by jhunt-steds** [Icinga/icinga-packaging#192]
Hello,

While installing Icinga Web on RHEL 8 using Apache httpd as my web server with PHP-FPM as recommended in the installation documentation, I encountered a problem. By default, the PHP-FPM installed as a dependency on RHEL 8 from the stock repos by running `dnf install icingaweb2 icingacli` listens on a Unix domain socket at /run/php-fpm/www.sock, whereas the supplied Apache configuration expects it to be listening on localhost:9000; see line 54 of /etc/httpd/conf.d/icingaweb2.conf, which reads:

```
SetHandler “proxy:fcgi://127.0.0.1:9000”
```

To work out of the box, it should be:

```
SetHandler “proxy:unix:/run/php-fpm/www.sock|fcgi://localhost/”
```

Alternately, I suppose a different PHP-FPM configuration could be supplied, but I didn’t research that option; anyway based on past experience using the default Unix-domain socket is likely to be more performant, though I haven’t measured it at all. Thanks!

**Comment by htriem** [comment]
Uh, that's not my area of expertise. @nilmerg does this ring any bell for you? Otherwise I'll research this.

**Comment by jhunt-steds** [comment]
I wish you luck, though I am no longer interested in this as we've gone with another option for our monitoring needs, so I'll be unsubscribing from this issue.

**Comment by nilmerg** [comment]
Nope, nothing ringing. I don't know what *supplied* means here. If placed by the package it should probably at least use a functional config. If we're talking about the `icingacli setup config webserver` command, that's just a default and would need to be adjusted by the user anyway.

**Comment by yhabteab** [comment]
> If we're talking about the icingacli setup config webserver command, that's just a default and would need to be adjusted by the user anyway.

Exactly! We do not provide FPM configurations in our packages and for the `icingacli setup config webserver` case one has to specify the desired uri using `--fpm-uri=...`. So, I'm closing this now!
