### ISSUE TITLE
Chocolatey Icinga 2.11.6 wrong version number

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#194]
Hello,

today Icinga 2.12.1 and Icinga 2.11.6 were released. The version number for the release 2.11.6 on Chocolatey is wrong: `Icinga 2 2.12.0.10`.

![image](https://user-images.githubusercontent.com/18580278/96176732-04003700-0f2d-11eb-8c7f-0ed78113e5b7.png)

https://chocolatey.org/packages/icinga2/2.12.0.10#versionhistory

Best regards
Michael

/cc @Al2Klimov @julianbrost

**Comment by N-o-X** [comment]
Should be fixed now. Thanks!
