### ISSUE TITLE
Debian package issue: 

### ISSUE THREAD

**Issue by deric** [Icinga/icinga-packaging#196]
When upgrading Debian package on Debian 10 buster
```
(Reading database ... 58084 files and directories currently installed.)
Preparing to unpack .../icinga2-ido-pgsql_2.12.1-1.buster_amd64.deb ...
/var/lib/dpkg/info/icinga2-ido-pgsql.prerm: 33: [: =: unexpected operator
Unpacking icinga2-ido-pgsql (2.12.1-1.buster) over (2.12.0-1.buster) ...
```

## To Reproduce

Upgrade `icinga2` package on Debian 10.

**Comment by Al2Klimov** [comment]
Hello again @N-o-X!

Any news from your side?

Best,
AK

**Comment by N-o-X** [comment]
Hi @deric,

sorry for the very late answer. I just tried upgrading from `2.12.0-1` to `2.12.1-1` with `icinga2-ido-pgsql` installed and didn't encounter any issues. Same thing with later versions.

Did this happen again during the last months while upgrading to other versions?

Greetings,
Noah

**Comment by htriem** [comment]
I can say with confidence that this isn't an issue anymore. Closed.
