### ISSUE TITLE
icingabeat missing in icinga-focal repository

### ISSUE THREAD

**Issue by trauta** [Icinga/icinga-packaging#197]
Hi,

the icingabeat .deb package seems to be missing in the icinga-focal repository [1] while the latest version v7.5.2 is available in the xenial repo [2].

[1] https://packages.icinga.com/ubuntu/dists/icinga-focal/main/binary-amd64/Packages
[2] https://packages.icinga.com/ubuntu/dists/icinga-xenial/main/binary-amd64/Packages

Regards,
Alexander

**Comment by Foxeronie** [comment]
We ran in this issue today too.
Only purely informative and without any hassle, do you know when this will be fixed?

**Comment by schnitzel4** [comment]
any solutions here? 
We have the same issue.
