### ISSUE TITLE
aarch64 packages for epel8?

### ISSUE THREAD

**Issue by FrostbyteGR** [Icinga/icinga-packaging#200]
[Since Centos8, aarch64 has become a main architecture](https://wiki.centos.org/About/Building_8#Main_architectures).
But [there don't seem to be any aarch64 packages available from the epel-8 icinga package repository](https://packages.icinga.com/epel/8/release/).
Seeing as there's some love for the arm platform in general ([as evident by the inclusion of Raspbian packages](https://packages.icinga.com/raspbian/)), could it be possible to start having aarch64 packages too, from epel-8 and onwards?

## Describe alternatives you've considered

If not, that's perfectly fine; I reckon one can still utilize the available SRPMs and build them by themselves.

Have a great day! :)

**Comment by Al2Klimov** [comment]
Hello again @theFeu!

Any news from your side?

Best,
AK

**Comment by htriem** [comment]
Closed as a duplicate, we'll continue the discussion in #220.
