### ISSUE TITLE
Make sure `/var/lib/icingaweb2` is utilizable

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icinga-packaging#208]
With Icinga Web 2.9 onwards we'd like to store runtime related data in there.

It's been [integrated](https://github.com/Icinga/icingaweb2/pull/3064) since a long time, but was never used.

Packages for the upcoming releases should set this directory up.

**Comment by nilmerg** [comment]
@dgoetz Does [this](https://github.com/Icinga/icingaweb2/blob/master/packages/selinux/icingaweb2.fc#L7) suffice to ensure this is writable if SELinux is enabled?

**Comment by dgoetz** [comment]
Yes, this will give `/var/lib/icingaweb2` a writable context.

**Comment by nilmerg** [comment]
Thanks!
