### ISSUE TITLE
[Debian] Packages for arm64/aarch64

### ISSUE THREAD

**Issue by Yoda-BZH** [Icinga/icinga-packaging#209]
Hello,

Can you please provide packages for arm64/aarch64 for Debian ?

With an increasing offer of arm64 servers and PCs, the need of those packages might increase too.

### Describe alternatives you've considered

Debian is providing arm64 packages, but not as up-to-date as yours.

Related issues for arm64 :
* #199 for ubuntu
* #200 for epel8

Thank you !

**Comment by htriem** [comment]
Closed as a duplicate, we'll continue the discussion in #220.
