### ISSUE TITLE
No php 7.4 for Centos7

### ISSUE THREAD

**Issue by inf0rmix** [Icinga/icinga-packaging#211]
Hi,

I have a Centos7 installation with rh-php73 .

I have search for php74 upgrades and they are not available. Is there any plan to support remi php 7.4 apache module ?

As far as I remember from upgrade last year, there is a dependency inside the rpm package for icingaweb2 which makes it impossible to install it with mod_php.

Is there any way to get it running with php 7.4 on Centos7 ?

**Comment by htriem** [comment]
I'd have to test this, but the most likely route will be us increasing the php version as a whole, which might happen next year.

**Comment by Al2Klimov** [comment]
Duplicate of #235
