### ISSUE TITLE
Debian Package should inform about or automatically apply migration sql scripts

### ISSUE THREAD

**Issue by cycloon** [Icinga/icinga-packaging#214]
## Is your feature request related to a problem? Please describe.
Recent versions of icingaweb2 (2.9.0 and 2.9.1) include sql upgrade scripts that need to be run against the database for all features to work correctly.

## Describe the solution you'd like
Debian an RPM Packages should either inform about those sql scripts and how to run them. Or even better, they should automatically run those sql scripts on behalf of the user. We could read icingaweb2.conf and identify the database, the user is using.

## Describe alternatives you've considered
Upgrade documentation is rarely read by users using RPM or Debian packages.

**Comment by htriem** [comment]
@nilmerg Any strong opinions on which way to go here?

**Comment by nilmerg** [comment]
Web has no schema version. So it's difficult to do anything mentioned here. Though, I'd just check and notify anyway, just like the icinga2 package does, does it?

**Comment by mpounsett** [comment]
It would make sense to at least include a "news" item in the `dpkg` so that admins are notified of the necessary upgrade.  Presumably RPM has a similar feature.

**Comment by yhabteab** [comment]
Recent Icinga Web 2 versions provide a built-in SQL migration automation `Configuration -> System -> Migrations`, so we don't need to build such for package installation/upgrades as well.
