### ISSUE TITLE
Virtual Server Installation Done But I can't See Anything

### ISSUE THREAD

**Issue by sehaartuc** [Icinga/icinga-packaging#215]
My IP + < ----> what should i write there ? for reacing icinga interface

**Comment by N-o-X** [comment]
Hi @sehaartuc! Please do not use GitHub issues to ask questions, but only to submit bug reports or feature requests. 

If you need help with your installation, have a look at the [installation documentation](https://icinga.com/docs/icinga-2/latest/doc/02-installation/). If that doesn't help, feel free to ask questions at our [community forums](https://community.icinga.com).

Greetings,
Noah
