### ISSUE TITLE
In the testing repository only icingadb 0.rc1.2.el8 is available

### ISSUE THREAD

**Issue by rhassing** [Icinga/icinga-packaging#216]
Is there a way to easy upgrade from icingadb-1.0.0-0.rc1.2.el8.icinga.x86_64 to icingadb-master?

**Comment by N-o-X** [comment]
Hi @rhassing! You can just use our snapshot repository for that. Those packages are based on the Icinga DB master and get updated daily. The testing repository is only used for release candidates of our software.

**Comment by htriem** [comment]
Can't add anything to that, @N-o-X.
