### ISSUE TITLE
List Debian 11 "bullyseye" as release build

### ISSUE THREAD

**Issue by mcktr** [Icinga/icinga-packaging#217]
Hi,

on http://packages.icinga.com/debian/ currently list `icinga-buster` and `icinga-stretch` as "Release Builds". On 14. August 2021 Debian 11 "Bullseye" was release. There are builds for `icinga-bullseye`, so please list it on the main page (if the are considered stable). 

* https://www.debian.org/News/2021/20210814

Thanks and best regards
Michael

**Comment by htriem** [comment]
The packages have been built, as far as I can tell, but you're right, it's still missing on the web page. I'm on it!

**Comment by RincewindsHat** [comment]
ping :-)

**Comment by htriem** [comment]
It's listed by now and everything is supported. I'll close this then.
