### ISSUE TITLE
raspian repo for "bullseye" has i386/amd64 files instead of armhf

### ISSUE THREAD

**Issue by Boris-de** [Icinga/icinga-packaging#218]
Hi,

I noticed that the repos in the "icinga-bullseye" and "icinga-bullseye-snapshots" folders for _raspbian_ wrongly contain `i386` and `amd64` packages instead of `armhf`. For raspbian buster it is (still) the expected `armhf`.

https://packages.icinga.com/raspbian/dists/icinga-bullseye/
https://packages.icinga.com/raspbian/dists/icinga-bullseye-snapshots/

Additionally the folders have not been updated since March (Edit: also they are just empty and don't contain any packages in their Packages files). I'm not sure if raspbian bullseye is even supposed to be supported yet, but having the folders available with a different architecture is a bit confusing at least.

Cheers,
Boris

**Comment by julianbrost** [comment]
At the moment we're not building packages for Raspbian bullseye. What's on packages.icinga.com are probably leftovers from an earlier attempt to add these, which was apparently never finished and as far as I know, there's also nobody currently working on this.

**Comment by htriem** [comment]
Closed as a duplicate, we'll continue the discussion in #220.
