### ISSUE TITLE
SLES repo file broken for releases newer than 12.3

### ISSUE THREAD

**Issue by udondan** [Icinga/icinga-packaging#219]
[Repo file](https://packages.icinga.com/SUSE/ICINGA-release.repo) looks like this:

```
[icinga-stable-release]
name=ICINGA (stable release for SUSE $releasever)
baseurl=https://packages.icinga.com/SUSE/$releasever/release/
enabled=1
gpgcheck=1
gpgkey=https://packages.icinga.com/icinga.key
```

The release index though looks like this:

![Bildschirmfoto 2021-08-23 um 10 50 56](https://user-images.githubusercontent.com/6443408/130418851-4013ce86-6a99-490c-a824-60edc8e7c021.png)

For whatever reason, the release directories don't follow a consistent pattern and don't match the `$releasever` since 12.4. For SLES 15 it's the reverse... 15.3. works, 15.2 and 15.1 won't.

We last tested this on August 18 without errors. Apparently there was a change regarding the snapshots repo on August 20. I assume something killed HTTP redirects or accidentally renamed the directories.

**Comment by N-o-X** [comment]
Hi @udondan,

thanks for reporting this issue!
You're right, the symlinks that where there until August 20th went missing while we cleaned up a bit.

The symlinks are back now, which should resolve this issue.

Greetings,
Noah

**Comment by udondan** [comment]
Awesome, thanks for the quick fix!
