### ISSUE TITLE
Unable to install on Rasberry Pi 3 with the current Pi OS Lite (Debian 11 based)

### ISSUE THREAD

**Issue by sqrt-1764** [Icinga/icinga-packaging#228]
I want to update my Pi, currently running the previous version of Rasberry OS Lite with Icinga2 working fine to the current version of Raspberry OS (based on Debian 11 Bullseye).

But the installation source for rasbian-bullseye seems to be broken. No installation candidate for icinga2. Same if I try bullseye-snapshots.

Trying to use the previous icinga-package (buster) results in missing dependencies when trying to install icinga2.

**Comment by gianmarco-mameli** [comment]
Hi, me too same problem, do you have a release date for Bullseye based packages? thanks

**Comment by sqrt-1764** [comment]
Any feedback?

**Comment by berrnd** [comment]
Noticed the same after upgrading my Pi's to Raspbian 11.

The packages are actually already present on the [Icinga Package Repository](https://packages.icinga.com/raspbian/):
- Fetch the repo key:
```
wget -O - https://packages.icinga.com/icinga.key | gpg --dearmor -o /usr/share/keyrings/icinga-archive-keyring.gpg
```
- Create `/etc/apt/sources.list.d/icinga.list` containing:
```
deb [signed-by=/usr/share/keyrings/icinga-archive-keyring.gpg] https://packages.icinga.com/raspbian icinga-bullseye main
```
- Continue as normal, works now

**Comment by julianbrost** [comment]
Packages for Raspbian bullseye should actually be there since December 1st. Looks like updating this issue was missed.
