### ISSUE TITLE
Missing icingaweb2 package for Raspbian Bullseye (armhf) 

### ISSUE THREAD

**Issue by XnS** [Icinga/icinga-packaging#230]
Hi,

for Raspbian Bullseye no `icingaweb2` package is available, snapshot repository is empty as well.

Regards,
~X

**Comment by htriem** [comment]
This concerns all of Raspbian Bullseye, we'll take a look at it in the next few days

**Comment by htriem** [comment]
Packages for Raspbian Bullseye are released by now. I'll close this one.
