### ISSUE TITLE
No package for Ubuntu 21.10 (impish)

### ISSUE THREAD

**Issue by Virsacer** [Icinga/icinga-packaging#232]
Hi, there is no package for Ubuntu 21.10 (impish) in https://packages.icinga.com/ubuntu/pool/main/i/icingaweb2/

**Comment by Virsacer** [comment]
@nilmerg Thanks for moving this Issue to the graveyard - I opened https://github.com/Icinga/icinga-packaging/issues/227 in this repo a few month ago...

**Comment by nilmerg** [comment]
Duplicate of #227
