### ISSUE TITLE
rpm packages for RHEL8-clones

### ISSUE THREAD

**Issue by m-erhardt** [Icinga/icinga-packaging#234]
I've noticed that you [stopped building/puplishing .rpm packages for CentOS 8](https://git.icinga.com/packaging/rpm-icingaweb2/-/commit/0d073b090ed0ecadd9aacf074f1b313b926cf3d1).

I am well aware of the CentOS 8 EOL but certainly lot's of people are using this repository on other subscription-free / community based RHEL8 clones like Rocky Linux, AlmaLinux or Oracle Linux.

Are there any plans to publish an .rpm repo for any of these distributions within the near future?
Otherwise everyone using this repo on one of these RHEL8 clones will have to change their systems to building/deploying from source.

**Comment by jeredfloyd** [comment]
Agreed; this is particularly an issue for security releases like 2.9.6 -- it would be great to have official (unsupported) packages available.

**Comment by gandihar** [comment]
If the development team doesn't want to use the "centos" name anymore, could we use something else like "epel" (Which appears to have broken with the above changes) or maybe "el8" (For RHEL8 offspring)? As stated above, AlmaLinux 8 and Rocky Linux 8 are going gangbusters out there, and Icinga not supporting EL8 systems is hurting this project, not their adoption.

**Comment by gandihar** [comment]
And now EL9 has been released by both RedHat and AlmaLinux. The Rocky 9 release is anticipated any day now.

Is there no one who can modify the Icinga2 packaging repo to use one of the other EL8 container images listed above?

**Comment by haxtibal** [comment]
> And now EL9 has been released by both RedHat and AlmaLinux. The Rocky 9 release is anticipated any day now.

We need EL9 compatible builds too, and would much appreciate if https://packages.icinga.com/ provided that builds. Meanwhile we'll have to build and archive RPMs internally.

It's not that hard, the [RPM source code](https://git.icinga.com/packaging/rpm-icinga2) is well maintained and suitable to build on any RHEL-9 clone. Here's an example how one can replay the [icinga-build-package](https://github.com/Icinga/docker-build-scripts/blob/master/icinga-build-package) workflow locally:

Enter a container with your target distirbution as clean build environment
```
docker run -ti --security-opt seccomp=unconfined --rm oraclelinux:9   # for me, clone3 syscalls would be prevented without seccomp=unconfined
```

Build .src.rpm and .rpm files
```
yum install -y wget curl which tar expect git patch rpm-build redhat-rpm-config rpmlint patch make util-linux yum-utils rpmdevtools createrepo
gitclone_dir="$HOME/git/rpm-icinga2" && mkdir -p "$gitclone_dir"
rpmbuild_topdir="$HOME/rpmbuild" && rpmdev-setuptree
git clone --depth 1 --branch 2.13.4-1 https://git.icinga.com/packaging/rpm-icinga2.git "$gitclone_dir"
spectool -g "$gitclone_dir/icinga2.spec" -C "$rpmbuild_topdir/SOURCES"
rpmbuild --nodeps -bs "$gitclone_dir/icinga2.spec"
yum-builddep -y "$rpmbuild_topdir/SRPMS/icinga2-2.13.4-1.el9.src.rpm"
rpmbuild --rebuild --define "vendor Icinga.com" --define "dist .el9.icinga" --define "_topdir $rpmbuild_topdir" "$rpmbuild_topdir/SRPMS/icinga2-2.13.4-1.el9.src.rpm"
```

After that, you'll end up with rpm files in `$rpmbuild_topdir/SRPMS/` and `$rpmbuild_topdir/RPMS/x86_64/`.
For a test, you can install icinga2 in your container environment
```
createrepo "$rpmbuild_topdir/RPMS/x86_64/"
dnf config-manager --add-repo file://$rpmbuild_topdir/RPMS/x86_64/
dnf --nogpgcheck install icinga2
```

**Comment by jeredfloyd** [comment]
@haxtibal : I agree and appreciate that spec files are still published.  I've ended up using Fedora Copr to generate my EL8 packages: https://copr.fedorainfracloud.org/coprs/jered/icinga2/

**Comment by haxtibal** [comment]
> I've ended up using Fedora Copr to generate my EL8 packages: https://copr.fedorainfracloud.org/coprs/jered/icinga2/

Thanks, that looks like a blueprint for EL9. Did you have to modify [icinga2.spec](https://copr-dist-git.fedorainfracloud.org/cgit/jered/icinga2/icinga2.git/tree/icinga2.spec?h=epel8) to make it buildable with Copr?

Or maybe even try to get icinga2 [into EPEL](https://docs.fedoraproject.org/en-US/epel/#how_can_i_contribute)? I mean, [Debian](https://packages.debian.org/sid/icinga2) and [Arch](https://aur.archlinux.org/packages/icinga2) have their own icinga2 packages, why not Fedora too?

But before further talking about community approaches, it would be nice to hear the opinion of Icinga devs. @lazyfrosch Any plans or ideas from your side regarding the future of `EL-*` builds? RHEL clones are widely adopted in industry, it's a bit surprising to see them deliberately excluded from your build machinery.

**Comment by jeredfloyd** [comment]
I didn't have to make any changes to the spec file to get things to work.  I could enable EL9 builds on that repo... I just am not using an EL9 at home yet.

I've been considering submitting it for EPEL, but I feel like it might be rude to the Icinga folks.  I don't want them to go out of their way to make it harder to do rebuilds (as, uh, Red Hat does) because that would be really disruptive for me.  So I'd want to hear a "sure, I guess" at least from Icinga devs.

**Comment by lazyfrosch** [comment]
@haxtibal I'm not involved with Icinga anymore, not able to help you.

**Comment by julianbrost** [comment]
> it's a bit surprising to see them deliberately excluded from your build machinery

That's not entirely correct, we continue to provide packages for RHEL which are available via a [subscription](https://icinga.com/subscription/), just like we started doing for other enterprise distributions. (In case you're missing RHEL 9 packages: yes, these took us a bit but most are online now and what's still missing should come rather soon.)

**Comment by haxtibal** [comment]
> we continue to provide packages for RHEL which are available via a [subscription](https://icinga.com/subscription/)

I've missed that, thank's for pointing out. IIUC this also answers @m-erhardt s original question and might be enough to close the issue?

**Comment by gandihar** [comment]
That's great for paid support, but those of us in the open source community who use a RH-family distro newer than 7 are on our own?

**Comment by bobapple** [comment]
There are currently plenty of different RHEL derivatives out there. Some of them are fully compatible with RHEL and some just claim to be. We don't have any plans to provide additional EL packages. An option currently being discussed is CentOS Stream. We'll try to figure out how high the adoption rate is under Icinga users and depending on that we may provide packages for that in the future.
