### ISSUE TITLE
Missing icinga 2.13.3 rhel8 packages

### ISSUE THREAD

**Issue by drapiti** [Icinga/icinga-packaging#238]
Icinga version 2.13.3 has been released however we cannot see the rhel8 build. Has it moved?

**Comment by julianbrost** [comment]
As CentOS 8 passed its end of life, packages for RHEL 8 (and other enterprise distributions) are now available with a subscription, please check [the blog post with the announcement](https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/) for more details.
