### ISSUE TITLE
Fedora 26 -- Icinga2

### ISSUE THREAD

**Issue by bittin** [Icinga/icinga-packaging#24]
Hello, is there any plans for building a new Icinga package for the Fedora release that got released today? 
The one for 25 does not work :(

**Comment by dnsmichi** [comment]
Tip from my experience with external repos in Fedora - don't immediately run fedup on release day for production environments. Give them time to catchup - especially on holiday season :)

**Comment by rubdos** [comment]
> Give them time to catchup - especially on holiday season :)

Honestly, their should be an issue about this the day of branching, such that the build is ready before release...

Maybe even a `rawhide` release :)

**Comment by rubdos** [comment]
For who's interested; I built icinga2 (not the web2) for x86_64 f26 https://www.rubdos.be/x86_64/

**Comment by lazyfrosch** [comment]
Fedora 26 builds have been published: https://packages.icinga.com/fedora/26/release/x86_64/
