### ISSUE TITLE
Installation for release build repo fails on Fedora >= 34

### ISSUE THREAD

**Issue by NavidSassan** [Icinga/icinga-packaging#241]
The installation instructions for the release builds for fedora try to install a non-existent file, for example for fedora 35: https://packages.icinga.com/fedora/icinga-rpm-release-35-latest.noarch.rpm. Can you either provide the repo-rpms for fedora 34 upwards, or adjust the installation instructions (to something similar to the testing-repo instructions)?

**Comment by yhabteab** [comment]
Packages have been available for the corresponding Fedora versions for some time now!
