### ISSUE TITLE
SUSE Repository URL is gone

### ISSUE THREAD

**Issue by Msaum87** [Icinga/icinga-packaging#246]
https://packages.icinga.com/SUSE/ no longer exists? My local RMT server last mirrored on 1 June 2022.
I saw an earlier issue with the same thing (https://github.com/Icinga/icinga-packaging/issues/221).

Thanks in advance
-Matthew

**Comment by julianbrost** [comment]
This repository was replaced with a subscription-base repository, see https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/ for more details.

The old one did not receive updates for some time and was now removed as announced in that blog post:

> Our old SLES packages will remain available until June 1, 2022.
