### ISSUE TITLE
SUSE / SLES Packages missing on packages.icinga.com

### ISSUE THREAD

**Issue by initnull** [Icinga/icinga-packaging#247]
Hi,

SLES Packges used to be under https://packages.icinga.com/SUSE/
since a while ago they seem to be missing.
SLES is still listed under supported plattforms https://icinga.com/subscription/support-matrix/
So is this an error? Do you still support SLES?

**Comment by lippserd** [comment]
Hi,

AL2, SLES, and RHEL packages are available through [subscription](https://icinga.com/subscription/).

All the best,
Eric

**Comment by initnull** [comment]
I see, thanks.
