### ISSUE TITLE
Sugestion to improve repo documentation apt-key is deprecated

### ISSUE THREAD

**Issue by basd82** [Icinga/icinga-packaging#251]
the use of apt-key is deprecated

i sugested the documentation www.icinga.com must be updated to :

```
curl https://packages.icinga.com/icinga.key | gpg --dearmour -o /usr/share/keyrings/Icinga.gpg

apt-get update

apt-get -y install apt-transport-https wget gnupg 

. /etc/os-release; if [ ! -z ${UBUNTU_CODENAME+x} ]; then 
DIST="${UBUNTU_CODENAME}"; else DIST="$(lsb_release -c| awk '{print $2}')"; fi; \
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/Icinga.gpg] https://packages.icinga.com/ubuntu icinga-${DIST} main" > \
/etc/apt/sources.list.d/${DIST}-icinga.list
echo "deb-src [arch=amd64 signed-by=/usr/share/keyrings/Icinga.gpg] https://packages.icinga.com/ubuntu icinga-${DIST} main" >> \
/etc/apt/sources.list.d/${DIST}-icinga.list
apt update
```

**Comment by julianbrost** [comment]
Random side note (just as a hint to incorporate when touching this): when the file is called `.asc`, APT should also be able to use ASCII-armored files directly. Alternatively, the binary file could also be put on the web server. Both would remove the need to install GnuPG explicitly.

**Comment by basd82** [comment]
Your right

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by chriscroome** [comment]
The documentation should probably also be updated to use [deb822 formatted repositories](https://repolib.readthedocs.io/en/latest/deb822-format.html#deb822-style-format), for example:

```bash
cat /etc/apt/sources.list.d/icinga.sources
```

```ini
Types: deb
URIs: https://packages.icinga.com/debian
Suites: icinga-bookworm
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/icinga.gpg
```

**Comment by Al2Klimov** [comment]
Fixed in https://github.com/Icinga/packages.icinga.com/pull/16
