### ISSUE TITLE
SUSE Linux Enterprise Server subtree missing 12.5/15.3/15.4

### ISSUE THREAD

**Issue by opensparcbox** [Icinga/icinga-packaging#255]
Hello,

**SLES** subtree with all files including subdirs with repos, files, packages are missing, e.g.
* [SUSE SLES12 SP5](https://packages.icinga.com/SUSE/12.5/release/)
* [SUSE SLES15 SP3](https://packages.icinga.com/SUSE/15.3/release/)
* [SUSE SLES15 SP4](https://packages.icinga.com/SUSE/15.4/release/)

![image](https://user-images.githubusercontent.com/41900420/179988692-314683ad-17e0-4e0d-816e-00c67c7b6f8b.png)

![image](https://user-images.githubusercontent.com/41900420/179985635-7801d073-c572-4f5f-a1b1-c595f44d4b27.png)

SUSE Linux Enterprise Server 12 Service Pack 5 has official base support until [31 Oct 2024](https://www.suse.com/lifecycle/), SLES15 SP3 and SP4 also still supported

Local subtree mirror expacted like...
![image](https://user-images.githubusercontent.com/41900420/179986949-3027dd97-f20b-4530-91fa-4c5a565a6537.png)
...with...
![image](https://user-images.githubusercontent.com/41900420/179987075-098e70e9-dc8a-4783-879a-eeaa20280754.png)

Missing subtree and files did not provide updates and fixes for SUSE Linux Enterprise Server, here major releases 12 and 15. Subtree within **openSUSE** looks like SLES15 ready but major release 12 still missing.

Maybe similar to issue #219 

Kind regards,
Stephan

**Comment by julianbrost** [comment]
We switched to providing packages for enterprise distributions on a subscription basis, see https://icinga.com/subscription/ for more details and https://icinga.com/blog/2022/02/16/announcing-official-icinga-packages-for-rhel-amazon-linux-2-and-sles/ for the initial announcement.
