### ISSUE TITLE
SELinux policy does not work on Fedora

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icinga-packaging#257]
## To Reproduce

1. Set up a fresh and up-to-date Fedora 36 system.
2. Install the `icinga2` and `icinga2-selinux` packages from packages.icinga.com
3. `systemctl start icinga2`
4. Observe that the process is running unconfined:
```
# ps -eZ | grep icinga2
system_u:system_r:unconfined_service_t:s0 2050 ? 00:00:00 icinga2
system_u:system_r:unconfined_service_t:s0 2076 ? 00:00:00 icinga2
system_u:system_r:unconfined_service_t:s0 2081 ? 00:00:00 icinga2
```

## Additional info

The command used by the `%post` scriptlet of the RPM fails to install the policy module:

```
# semodule -s targeted -i /usr/share/selinux/targeted/icinga2.pp
Failed to resolve roleattributeset statement at /var/lib/selinux/targeted/tmp/modules/400/icinga2/cil:46
Failed to resolve AST
semodule:  Failed!
```

(No error is visible during the actual package installation.)

## Your Environment

* Version used (`icinga2 --version`): r2.13.4-1
* Operating System and version: Fedora Linux 36 (Cloud Edition)

**Comment by lippserd** [comment]
Fixed by Icinga/icinga2#9664.
