### ISSUE TITLE
Previously available packages for Ubuntu 18.04 have disappeared from repo

### ISSUE THREAD

**Issue by ahktenzero** [Icinga/icinga-packaging#258]
I tried installing Icinga on an Ubuntu 18.04 container from the repo you provide and ran into a load of errors. The main problem is that the Packages file for the ubuntu-bionic dist lists the most recent versions of icinga2-bin and icinga2-common as 2.13.3-1, but the deb files for these versions are no longer in the repo. The most recent version for which they are still available is 2.12.4-1. I have other systems running 18.04 which have 2.13.3 installed so they must have been removed at some point. I have seen #252 and understand that 18.04 is no longer supported and I don't expect to see more recent versions packaged for it, but that doesn't explain why previously existing packages have been removed. Was this intentional?

Also, doc/04-OS-EOL.md still lists 18.04 as supported until the Ubuntu EOL date next year (and doesn't mention 20.04 or 22.04), if this is no longer the case it should be updated.

**Comment by julianbrost** [comment]
`icinga2_2.13.3-1.bionic_amd64.deb` etc. are still online at https://packages.icinga.com/ubuntu/pool/main/i/icinga2/, so I don't think that anything was removed.
