### ISSUE TITLE
Spec files for EL8/9

### ISSUE THREAD

**Issue by willfurnell** [Icinga/icinga-packaging#259]
Hello,
As far as I can see through various discussions - 
https://community.icinga.com/t/package-support-for-almalinux-8-rockylinux-8/9864
https://community.icinga.com/t/icinga-repository-for-suse-not-up-to-date/9696
https://community.icinga.com/t/how-to-build-your-own-icingaweb2-packages-for-centos-8-as-the-security-fix-was-not-released-for-it/9390

you do not provide packages for CentOS/Alma/Rocky etc. versions 8 and 9, and that if we want to use these OS' we need to build these packages ourselves. However, I am unable to find the EL8 .spec file you are using for building EL8 packages currently. Please could you provide the spec file we should be using for building our own EL8/EL9 packages,

Thanks,

Will.

**Comment by lippserd** [comment]
Hi,

Packages for enterprise distributions like RHEL are available via [subscription](https://icinga.com/subscription/).

All the best,
Eric

**Comment by willfurnell** [comment]
@lippserd I'm aware about the packages, but I'm not asking about those. I'm asking about the .spec files to build the packages myself. Thanks.

**Comment by wiza** [comment]
https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec

I'm toying with the idea to publish packages for non-enterprise EL8 (and in future 9) distributions which are currently not covered.

**Comment by flybyray** [comment]
> I'm toying with the idea to publish packages for non-enterprise EL8 (and in future 9) distributions which are currently not covered.

Any progress? Help needed?
Maybe hosting packages on GitHub.io is possible too: https://github.com/cpriest/repo/tree/gh-pages

**Comment by wiza** [comment]
I have docker files for icinga2 for rockylinux 8 and 9 ready, icingaweb2 pending and I have tested those on my own systems and seem to be working.

**Comment by wiza** [comment]
Little polishing and I'll make the github repo public, I'm also thinking about public RPM repo (currently running private repo).

**Comment by igor-sweet** [comment]
Love to see community EL 8/9 support coming back to life.

**Comment by willfurnell** [comment]
Interestingly they are no longer publishing ANY spec files publicly - https://git.icinga.com/packaging/rpm-icinga2/-/raw/master/icinga2.spec is now in a read-only repository...

**Comment by igor-sweet** [comment]
So you have to Pay an unknown amount of money for an Icinga-RHEL subscription, without the underlying RHEL OS. Or migrate to Ubuntu or Debian in the hope, that the support will continue there
