### ISSUE TITLE
package icinga2-common:all differs between debian and raspbian

### ISSUE THREAD

**Issue by qyanu** [Icinga/icinga-packaging#262]
Hallo,

a comparison of
* https://packages.icinga.com/raspbian/pool/main/i/icinga2/icinga2-common_2.13.5-1.bullseye_all.deb
and 
* https://packages.icinga.com/debian/pool/main/i/icinga2/icinga2-common_2.13.5-1.bullseye_all.deb
reveals, that

- one package uses Priority optional, the other Priority extra.
- one package points to homepage https://www.icinga.com the other to http://www.icinga.org (an url without a proper web page)
- in the changelog.Debian file, the timestamps differ hinting to non-repeatable packaging scripts
- in the changelog.Debian file, some typos are different.

These differences lead to different checksums, making it a real problem shipping icinga2 architectures amd64 as well as armhf in a single deb repository.

couldn't the build process be unified and thus leading to repeatable packaging with binary-equal content of arch "all" packages?

best regards,

Max

**Comment by qyanu** [comment]
fixed typo in original issue description; i gave the raspbian url twice. the rest of the description still holds.

**Comment by julianbrost** [comment]
Did you check that for any newer packages? By now, we build them from a common source, so the differences in the priority and homepage should be gone. Also, the Debian and Raspbian packages now use different version numbers (`2.14.0-1+debian11` / `2.14.0-1+raspbian11`) so putting them in a common repo pool should no longer be a problem.

**Comment by qyanu** [comment]
I rechecked with the versions "2.14.0-1+debian11" and "2.14.0-1+raspbian11", and they are very similar (not identical) now. they have a changelog a few seconds apart [+], and were built with different build helper versions. all other differences are a direct consequence of that.

* hosting mixed repository mirror (with armhf from /raspbian and arm64 from /debian) is indeed possible now, as the file names are different.

* closing this issue, because as you say the building from common source really made the metadata differences go away


[+] when i had to guess, the "building from same source" first makes for each target a separate dsc file, and then builds the binary packages from that. and while building both targets from the same dsc file (and thus identical changelog), this is probably not worth the effort.

**Comment by julianbrost** [comment]
Yes, the source packages are built per distribution and version (counting Debian, Ubuntu and Raspbian (= Raspberry Pi OS 32bit, the 64bit variant is pretty much Debian with some extra packages) as separate distributions) as that's where the version suffix like `+debian11` is inserted into the changelog.
