### ISSUE TITLE
No i386 packages for version 2.13.6?

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icinga-packaging#265]
Hi,

since version 2.13.6 there are no i386 packages in the repository.
Is this intended? Was there an announcment to drop i386 support?

Having a few old systems still running i386 it broke our installations with the newest update.
icinga2-common was updated to 2.13.6 (because off the "all" architecture), but icinga2 and icinga2-bin were
removed because they can't get their dependencies for icinga2-common matched.

Thanks
Stefomat

**Comment by taladar** [comment]
We can confirm this issue, specifically on Debian buster we have the same issue.

i386 packages are not necessarily crucial for us but some sort of official statement on whether this is a bug or by design would be nice.

**Comment by Stefomat** [comment]
I tried using `dpkg --add-architecture amd64 `to be able to install the amd64 packages. Unfortunately, that didn't work out. It always fails because of the icinga2-common package, which supposedly does not fulfil the dependency for icinga2 and icinga2-bin. Does anyone have experience with this constellation? I don't want to stay on the old Icinga version.

**Comment by Stefomat** [comment]
I got it working by rebuilding the icinga2-common package. I modified the field "Architecture" in the control file so that it no longer says "all" but "amd64". After that, the package could be successfully installed as a dependency.
The following steps were necessary.
```
dpkg-deb --extract icinga2-common_2.13.6-1+debian11_all.deb ./icinga2-common_2.13.6-1+debian11_all
dpkg-deb --control icinga2-common_2.13.6-1+debian11_all.deb ./icinga2-common_2.13.6-1+debian11_all/DEBIAN
nano ./icinga2-common_2.13.6-1+debian11_all/DEBIAN/control
dpkg --build ./icinga2-common_2.13.6-1+debian11_all icinga2-common_2.13.6-1+debian11_amd64.deb
```
```
--- a/icinga2-common_2.13.6-1+debian11_all/DEBIAN/control
+++ b/icinga2-common_2.13.6-1+debian11_all/DEBIAN/control
@@ -1,7 +1,7 @@
 Package: icinga2-common
 Source: icinga2
 Version: 2.13.6-1+debian11
-Architecture: all
+Architecture: amd64
 Maintainer: Icinga Development Team <info@icinga.com>
 Installed-Size: 530
 Depends: adduser, lsb-release, lsb-base
```

However, this cannot be a permanent fix for the problem as it is not suitable for productive use. Why icinga2 and icinga2-bin insist on the architecture amd64, I still do not understand.

**Comment by julianbrost** [comment]
Sorry for the long wait, but at least now I have some good news right away: Since yesterday, there are i386 packages for Debian on packages.icinga.com again.
