### ISSUE TITLE
No packages for Ubuntu 22.10 (kinetic)

### ISSUE THREAD

**Issue by fabieins** [Icinga/icinga-packaging#267]
Hi,
Ubuntu 22.10 (kinetic) has been released last month, but it is missing in the [Icinga Package Repository](https://packages.icinga.com/ubuntu/dists/).

**Comment by moreamazingnick** [comment]
I think packages.icinga.com only supports Ubuntu LTS 

see agent section
https://icinga.com/subscription/support-matrix/

but there is a recent package in the ubuntu repo
https://packages.ubuntu.com/kinetic/icinga2

**Comment by fabieins** [comment]
Too bad, after over seven years.

**Comment by fabieins** [comment]
Too bad, after over seven years.
