### ISSUE TITLE
Missing vendor on sles12 package 2.13.6

### ISSUE THREAD

**Issue by 5im0n1** [Icinga/icinga-packaging#273]
Hello,

we cant upgrade our icinga2 version via workflow on SLES12 because of missing vendor entry.

https://packages.icinga.com/subscription/sles/12.5/release/x86_64/icinga2/icinga2-2.13.6-1.x86_64.rpm
![icinga2 13 6](https://user-images.githubusercontent.com/122433050/211744571-133dfefc-31da-4bc1-9ea6-e40f34b901cb.png)

Could you please include the vendor entry?
![icinga2 13 5](https://user-images.githubusercontent.com/122433050/211746126-489f5279-2f4a-4665-8226-0cb12ad96af5.png)

kind regards
Simon

**Comment by htriem** [comment]
A revision of 2.13.6 has been released, 2.13.6-2 , with the vendor information set to `Icinga GmbH`. This change will apply to all packages in the Icinga ecosystem - we're in the process of streamlining our packaging and building more uniform packages. So be advised of the vendor information changing.
