### ISSUE TITLE
Incomplete Repository Fedora 37

### ISSUE THREAD

**Issue by mightbeuseless** [Icinga/icinga-packaging#274]
Hello,

under https://packages.icinga.com/fedora/37/release/ there are no folders (e.g. /src) which contain the packages.  

While upgrading our fedora coreos nodes we get the following errormessage: "error: Packages not found: icinga2"

Best Regards

**Comment by htriem** [comment]
Our packages for Fedora 37 have been released, so I'll close this. Good luck with the upgrade!
