### ISSUE TITLE
IcingaDB redis service in docs

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icinga-packaging#282]
In the documentation of Icingadb-redis under debian you are advised to start the service `icingadb-redis`. However, this service does not exist under debian. There it can be found under `icingadb-redis-server`

Failure while starting `icingadb-redis`:
`Failed to enable unit: Too many levels of symbolic links`

On Ubuntu the service `icingadb-redis` also only points to `icingadb-redis-server`.
```
$ systemctl status icingadb-redis
● icingadb-redis-server.service - Advanced key-value store
...
```

## To Reproduce

* Install icingadb-redis on Debian
* try `systemctl enable --now icingadb-redis`

## Expected behavior

The service should be named on all distros the same.

**Comment by tbauriedel** [comment]
ref/NC/778073

**Comment by tbauriedel** [comment]
Any progress on this topic?

**Comment by oxzi** [comment]
FYI, there is <https://github.com/Icinga/icinga2/pull/9877> adjusting the documentation.

**Comment by Al2Klimov** [comment]
Duplicate of https://github.com/Icinga/icinga2/issues/9511
