### ISSUE TITLE
Cube: RHEL 7 / RHEL 8 Packages are not usable due to incorrect file paths

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icinga-packaging#284]
## Describe the bug

Execute a `repoquery --list icinga-cube-web.noarch`
RHEL 7:
![image](https://user-images.githubusercontent.com/67681686/230038188-4de0c322-a9f2-4bb2-b7a2-a6c0a47836b6.png)

RHEL 8:
![image](https://user-images.githubusercontent.com/67681686/230038012-08432ba4-6802-4db7-ad74-5d34657909a4.png)

In both cases the files below `/usr/share/icingaweb2/modules` should be installed in `/usr/share/icingaweb2/modules/cube/` instead.
qq
Second issue - which arises from this - is you can not remove the package anymore.
![image](https://user-images.githubusercontent.com/67681686/230038681-a2c1329c-ffd8-4588-be07-ac691543889c.png)

## To Reproduce

Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. `yum install icinga-cube.noarch` / `dnf install icinga-cube.noarch`

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): Icinga Web 2  2.11.4
* PHP version used (`php --version`): PHP Version   7.3.33
* Server operating system and version: RHEL 7 / RHEL 8

**Comment by nilmerg** [comment]
A `1.3.0-2` should be available now, which fixes this issue.
