### ISSUE TITLE
Debian 12 bookworm packages missing

### ISSUE THREAD

**Issue by mferstl** [Icinga/icinga-packaging#287]
Debian 12.0 was released on June 10th, 2023.

Perhaps it should be added to the build-system.

**Comment by jfrede** [comment]
I'm also waiting for this packages to update some VMs.

**Comment by htriem** [comment]
Icinga 2 2.13.7 and 2.12.10 have been released for Debian 12 Bookworm, so I'll close this.

**Comment by dm8tbr** [comment]
JFTR, while the main package is there - and this ticket was justifiably closed based on that - it seems some are still missing: https://github.com/Icinga/icinga-packaging/issues/290
I'm _guessing_ this is work in progress. Wanted to leave a cross-reference, just in case someone finds this but not the other ticket.
