### ISSUE TITLE
Package icingaweb2-module-monitoring missing in the release file.

### ISSUE THREAD

**Issue by franciscotw** [Icinga/icinga-packaging#289]
Hello Icinga Team,

We noticed yesterday our nightly deployments started failing, and the reason was the `icingaweb2-module-monitoring` package was missing from the Icinga repository [release file](https://packages.icinga.com/debian/dists/icinga-bullseye/main/binary-amd64/Packages) and since the latest `icingaweb2-module-monitoring` in the Debian repository is `2.8.2-2`, it breaks.
This is happening in Debian 11 bullseye.

If there is anything else we can support with, please reach us out.

Best regards,
Francisco

**Comment by lippserd** [comment]
@franciscotw Thanks for reporting!

@htriem Can you please have a look?

**Comment by earl-warren** [comment]
I confirm this. Where can it be found? A workaround would be useful, it is breaking deployments.

**Comment by earl-warren** [comment]
It is also missing from the pool https://packages.icinga.com/debian/pool/main/i/icingaweb2-module-monitoring/. There is only debian 10 there, no debian 11.

![image](https://github.com/Icinga/icinga-packaging/assets/109468362/e5a0e98e-da76-4b3d-8751-5a9225b3590c)

**Comment by julianbrost** [comment]
What exactly is the action that results in an error? Do you actively try to install the `icingaweb2-module-monitoring` package? Or do you get some kind of dependency error when installing some other package?

Note the description from that package, so you shouldn't need that package at all:

```
Description: Empty transition package
 Icinga Web 2.11.4 has removed the monitoring module package.
 To ease upgrading, this is an empty transition package with no dependencies.
```

**Comment by earl-warren** [comment]
It is part of an Ansible playbook which should just **not** install that :-)

**Comment by lippserd** [comment]
Uploaded.
