### ISSUE TITLE
Package icinga-director missing on Debian Bookworm

### ISSUE THREAD

**Issue by RafaelSche** [Icinga/icinga-packaging#291]
## Current Behavior
```sh
$ sudo apt install icingaweb2-module-director
...
The following packages have unmet dependencies:
 icingaweb2-module-director : Depends: icingaweb2-module-monitoring but it is not installable
E: Unable to correct problems, you have held broken packages.

$ sudo apt install icingaweb2-module-director
...
The following packages have unmet dependencies:
 icingaweb2 : Breaks: icingaweb2-module-monitoring (< 2.12.0-1+debian12) but 2.11.4-2 is to be installed
 icingaweb2-module-monitoring : Depends: icingaweb2 (= 2.11.4-2) but 2.12.0-1+debian12 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

So icingaweb2-module-director depends on icingaweb2-module-monitoring, which depends on an older version of icingaweb2.
But I don't need icingaweb2-module-monitoring, because I'm using the IcingaDB. Is that an old dependency? On Debian Bullseye there was a package called "icinga-director", which does not have this dependency. But it is not available for bullseye. Is it supposed to be replaced by icingaweb2-module-director?

## Expected Behavior
Package icingaweb2-module-director should be installable.

## Possible Solution
Remove icingaweb2-module-monitoring as dependency.

## Steps to Reproduce (for bugs)
See above.

## Your Environment

* Director version (System - About): 1.10.2-1
* Icinga Web 2 version and modules (System - About): 2.12.0
* Icinga 2 version (`icinga2 --version`): r2.14.0-1
* Operating System and version:  Debian GNU/Linux 12 (bookworm) ; Kernel: Linux 6.1.0-12-amd64;
* Webserver, PHP versions: Apache2: 2.4.57-2; PHP 8.1.23;

**Comment by julianbrost** [comment]
`icingaweb2-module-director` is the package provided by Debian itself, not by `packages.icinga.com`. You generally don't want to mix those.

The actual problem seems to be that our own `icinga-director` packages weren't uploaded for Debian 12 (bookworm) so far: https://packages.icinga.com/debian/pool/main/i/icinga-director/

**Comment by yhabteab** [comment]
> The actual problem seems to be that our own `icinga-director` packages weren't uploaded for Debian 12 (bookworm) so far: https://packages.icinga.com/debian/pool/main/i/icinga-director/

They're available now!
