### ISSUE TITLE
icingaweb2-2.11.4 not installable anymore on CentOS7

### ISSUE THREAD

**Issue by Decstasy** [Icinga/icinga-packaging#293]
## Describe the bug
Looks like a dependency hell. I cannot install `icingaweb2-2.11.4` even by installing icingaweb2 and trying a `yum downgrade icingaweb2-2.11.4`.

## To Reproduce
Take a fresh CentOS 7 VM (e.g. vagrant box) and try to install it:

```bash
rpm --import https://packages.icinga.com/icinga.key
wget https://packages.icinga.com/centos/ICINGA-release.repo -O /etc/yum.repos.d/ICINGA-release.repo
yum install epel-release
yum install centos-release-scl
yum install icingaweb2-2.11.4 icingacli-2.11.4
```

I even tried to fiddle with all the dependencies etc. it is simply not working anymore because smart people tend to do stuff without knowing the consequences. Why do we even have versioning?

## Expected behavior
A installation to a specified version is possible like it should be.

## Screenshots
Too much output, look here https://gist.github.com/Decstasy/1e6946161ae976950a9408f362772cfe 

## Your Environment
```
CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.9.2009 (Core)
CentOS Linux release 7.9.2009 (Core)
```

## Additional context
The newest version is installable BUT I have good reasons to use the 2.11.4, this has to work.

**Comment by yhabteab** [comment]
Hi @Decstasy, thanks for reporting!

I do fully understand your frustration and sorry for the delay! I was also able to reproduce your exact situation and it seems that `yum` does some unexpected things with packages that obsolete other ones. According to [Redhat](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-configuring_yum_and_yum_repositories), obsoletes are only processed during `yum update`, but on Centos7 it does process *obsoletes* when performing `yum install`, so I'm not sure whether `yum` does different things on Centos7 than it does on Rhel distros.

If you are still struggling with this issue and still want to install Icinga Web 2 `< 2.12.0`, you can use the following command. This will explicitly prevent `yum` from processing obsolete packages (`Obsoletes: ....` instructions in the spec file). `yum --setopt=obsoletes=0 install icingaweb2-2.11.4`

**Comment by Decstasy** [comment]
Hi @yhabteab ,
thanks for reproducing and providing a workaround for this issue :+1:
