### ISSUE TITLE
Incomplete Repository Fedora 39

### ISSUE THREAD

**Issue by rbicker** [Icinga/icinga-packaging#296]
Hi

Under https://packages.icinga.com/fedora/39/release/, the only folder available is "repodata".  Therefore we are unable to install the icinga2 package on Fedora 39 servers. We have tried to use the Fedora 38 repository but this does not work (not sure if the deprecation of modular dnf repository is also part of the problem).

Thanks for your help

**Comment by yhabteab** [comment]
Hi, the packages are available since a while now!
