### ISSUE TITLE
systemd Dependencies incorrect

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icinga-packaging#3]
From @sahnd in https://github.com/Icinga/icinga2/issues/4915#event-952549320

> I think there is a typo in the systemd service file:
> Line 3, "yslog.target" should probably be "syslog.target".
> 
> In addition there should be a dependency for "network-online.target" or "network.target", because otherwise Icinga2 will fail to start after reboot, when api is bound to a specific IP.

**Comment by lazyfrosch** [comment]
To be checked for RPM as well

**Comment by formorer** [comment]
ubuntu, fixed in: 7268104
debian , fixed in: 16eb968

I won't do a an upload for that, since we have a bugfix release next week

**Comment by lazyfrosch** [comment]
I think we can close this issue then.

**Comment by lazyfrosch** [comment]
Thanks @formorer

**Comment by lazyfrosch** [comment]
ah damn, wrong issue to close :man_facepalming:
