### ISSUE TITLE
Ubuntu 24.04 icingadb-redis packages missing

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga-packaging#304]
I just fired up hyperv and wanted to prepare a new test-machine and noticed that icingadb-redis is missing for ubuntu 24.04.

Thanks in advance and
Best Regards

Nicolas

**Comment by trauta** [comment]
Running into the same issue, since Ubuntu 24.04 is [officially supported](https://icinga.com/subscriptions/support-matrix/) I'd expect all major packages to be available :/

**Comment by Al2Klimov** [comment]
Hello and thank you for reporting!

The packages have been released, see:

https://icinga.com/blog/2024/06/26/new-redis-open-source-server-packages-for-icinga-db/

Best,
A/K
