### ISSUE TITLE
Fedora 41 packages

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga-packaging#309]

**Comment by Al2Klimov** [comment]
# Blocked by

* [x] https://github.com/moby/buildkit/issues/5502

**Comment by julianbrost** [comment]
That issue suggests that using syntax version 1.11.0 still works. Is there something that would prevent us from using that. So is it really blocked? Or could it be worked around easily?

Also, as this issue tracker is public and in case anyone wonders how the hell that's related to Fedora 41 packages: the Dockerfiles we use to build the container images we use to build the packages inside use `syntax=docker/dockerfile:1.10.0`, so without putting extra work in, these builds currently fail, i.e. we don't have a suitable Fedora 41 container in our build environment at the moment.
