### ISSUE TITLE
Icinga2 Repository not working

### ISSUE THREAD

**Issue by amithpat** [Icinga/icinga-packaging#35]
http://packages.icinga.com/epel/7Client/release/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by lazyfrosch** [comment]
Oh interesting, we haven't created symlinks for desktop clients yet. But it should be the same repo.

Which distribution are you using? RedHat Enterprise Desktop?

/cc @dgoetz

**Comment by amithpat** [comment]
Oh  sorry this is wiered. I am not sure how I downloaded this

Red Hat Enterprise Linux Client release 7.2 (Maipo)
NAME="Red Hat Enterprise Linux Client"
VERSION="7.2 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Red Hat Enterprise Linux Client 7.2 (Maipo)"
ANSI_COLOR="0;31"


On 8/20/17, Markus Frosch <notifications@github.com> wrote:
> Oh interesting, we haven't created symlinks for desktop clients yet. But it
> should be the same repo.
>
> Which distribution are you using? RedHat Enterprise Desktop?
>
> /cc @dgoetz
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Icinga/icinga-packaging/issues/35#issuecomment-323569695


-- 
Regards,
Amith

**Comment by dgoetz** [comment]
Symlinking 7Client to 7 should be fine as 7Client is mainly a different collection of packages so packages should work fine. For support it should also make no difference. But EPEL repository does also not provide a symlink, so it will probably also fail to get the plugin packages.

**Comment by lazyfrosch** [comment]
Looks like EPEL does not use `$releasever` in the default release RPMs:

```
[epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
...
```

I'll create the symlinks...

**Comment by lazyfrosch** [comment]
Symlink have been created: https://packages.icinga.com/epel/
