### ISSUE TITLE
RPMs: icingaweb2-vendor-dompdf should depend on php-mbstring

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#38]
Users reported this here: https://monitoring-portal.org/index.php?thread/41629-pdf-export-fatal-error/&postID=255425#post255425

I've also received a patch for the Vagrant boxes lately: Icinga/icinga-vagrant#85

**Comment by Mikesch-mp** [comment]
If you are on it, php 7+ needs dompdf 0.8 to work, maybe just upgrade the lib to 0.8 in next release

**Comment by lazyfrosch** [comment]
Stalled for now, I need to review the package names and versions on the individual distros.

This could break badly else :)

**Comment by dnsmichi** [comment]
dompdf will be replaced with something else sooner or later, so this isn't relevant anymore imho. Feel free to close.

**Comment by dnsmichi** [comment]
reporting uses pdfexport, Icinga Web 2 will use that sooner or later. Not relevant anymore.
