### ISSUE TITLE
No 2.7.0 on Ubuntu 14.04

### ISSUE THREAD

**Issue by vaisov** [Icinga/icinga-packaging#39]
Currently latest version for 14.04 in the repo is 2.6.3

**Comment by lazyfrosch** [comment]
Hmm, [our repo](https://packages.icinga.com/ubuntu/dists/icinga-trusty/main/binary-amd64/Packages) says:

```
Package: icinga2
Priority: extra
Section: admin
Installed-Size: 46
Maintainer: Icinga Development Team <info@icinga.com>
Architecture: amd64
Version: 2.7.0-1.trusty
Depends: icinga2-bin (= 2.7.0-1.trusty), icinga2-common (= 2.7.0-1.trusty)
Recommends: icinga2-doc (= 2.7.0-1.trusty), monitoring-plugins-basic | nagios-plugins-basic, libreadline6
Suggests: icinga2-studio, vim-icinga2
Filename: pool/main/i/icinga2/icinga2_2.7.0-1.trusty_amd64.deb
```

What repository are you using?

**Comment by vaisov** [comment]
`Package: icinga2
Priority: extra
Section: admin
Installed-Size: 46
Maintainer: Debian Nagios Maintainer Group <pkg-nagios-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 2.6.3-1~ppa1~trusty1
Recommends: icinga2-doc (= 2.6.3-1~ppa1~trusty1), monitoring-plugins-basic | nagios-plugins-basic, libreadline6
Suggests: icinga2-studio, vim-icinga2
Depends: icinga2-bin (= 2.6.3-1~ppa1~trusty1), icinga2-common (= 2.6.3-1~ppa1~trusty1)
Filename: pool/main/i/icinga2/icinga2_2.6.3-1~ppa1~trusty1_amd64.deb
`

I'm using `deb http://ppa.launchpad.net/formorer/icinga/ubuntu trusty main` added using `add-apt-repository`

**Comment by lazyfrosch** [comment]
The PPA is an alternative repository maintained by @formorer. I think he fixed something regarding trusty builds recently.

This tracker is for packages hosted on [packages.icinga.com](https://packages.icinga.com).
