### ISSUE TITLE
Add SLES 12 SP3 packages

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#40]
Was released some days ago.

https://www.suse.com/releasenotes/x86_64/SUSE-SLES/12-SP3/

**Comment by dgoetz** [comment]
Do we want to drop SLES 12 SP1 as General Support ended "31 May 2017"? Or at least stop building newer packages? https://www.suse.com/lifecycle/

**Comment by lazyfrosch** [comment]
Seems like they released it about 2 weeks ago

    SUSE Linux Enterprise Server 12 SP3 - 07 Sep 2017

I guess we should not build 1.8 for SP1 then.

**Comment by dnsmichi** [comment]
Just remove the build jobs for SP1 then, but keep the binary packages around. Thanks for noticing, I though SLES service packs have a longer livecycle.

**Comment by lazyfrosch** [comment]
I noticed they are preparing SP3, but the release wasn't out then.

https://www.suse.com/lifecycle/

**Comment by lazyfrosch** [comment]
Docker images are currently building. Will build the releases afterwards.

Note for @lippserd: SLES 12 SP1 has been removed from the builds

**Comment by lazyfrosch** [comment]
Builds are out: https://packages.icinga.com/SUSE/12.3/release/
