### ISSUE TITLE
Web 2: Raise PHP dependency to version 5.6 and use PHP-FPM

### ISSUE THREAD

**Issue by lippserd** [Icinga/icinga-packaging#41]

**Comment by CLNRMN** [comment]
@lippserd 
In referenced from [https://github.com/Icinga/icingaweb2/issues/2847](url), we want to know if there is any news for icinga SCL packaging?

Because since icingaweb2-module-director 1.4 has dropped php 5.3 we want to migrate to php 7.0.

**Comment by lippserd** [comment]
This is a task for our next Icinga Web 2 release version 2.5.0 which is scheduled for the end of November.

**Comment by lazyfrosch** [comment]
Fixed in #60
