### ISSUE TITLE
Debian/Ubuntu binary-amd64 Package file not up-to-date

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#44]
binary-amd64 "Packages" file is not updated on release publish. It is created with the current timestamp, but does not contain 2.7.1 (the latest release).

This does not harm package setup though, you'll get the proper package running apt-get update and so on.

```
docker run -ti debian bash

apt-get update && apt-get -y install wget gnupg apt-transport-https
wget -O - https://packages.icinga.com/icinga.key | apt-key add -
echo 'deb https://packages.icinga.com/debian icinga-stretch main' >/etc/apt/sources.list.d/icinga.list
apt-get -y install icinga2
icinga2 daemon -apt-get -y install icinga2

root@f6bf06b9de4f:/# dpkg -l icinga2
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                            Version              Architecture         Description
+++-===============================-====================-====================-====================================================================
ii  icinga2                         2.7.1-1.stretch      amd64                host and network monitoring system
```

The same applies to all Ubuntu versions, we had that in this thread here: 
https://monitoring-portal.org/index.php?thread/41813-icinga2-notifications-not-working-properly-after-upgrade/&postID=256206#post256206

If I re-run the publish job for Debian Stretch, it works.

**Comment by lazyfrosch** [comment]
Well we basically trigger the publish via aptly's API.

I guess I should have a look on updating the version...

**Comment by lazyfrosch** [comment]
Latest builds for icingaweb2 2.4.2 and Icinga2 2.7.1-2 worked without a problem.

Not sure what happened there... Closing for now should be better I guess
