### ISSUE TITLE
Missing dependency: php-xml on Debian/Ubuntu

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga-packaging#51]
PR: coming soon

**Comment by Al2Klimov** [comment]
While testing my changes I discovered that IW2 itself already depends on php-xml... but I installed just icingaweb2 from the builtin package sources – and there was no such dependency.

@lazyfrosch Are you sure that this repo is the "Correct place to update" this (https://github.com/Icinga/icingaweb2/pull/3009)? I guess Debian/Ubuntu don't build their packages form *this* repo.

**Comment by lazyfrosch** [comment]
Yes this is the repository we are building packages from.

Upstream Debian is another issue, Ubuntu is just copying packages from Ubuntu.

**Comment by Al2Klimov** [comment]
"Upstream Debian is another issue" – damn.
