### ISSUE TITLE
No longer seeing current snapshots

### ISSUE THREAD

**Issue by druchoo** [Icinga/icinga-packaging#52]
I was using https://packages.icinga.com/epel/7/snapshot/noarch/ to test latest commits of IcingaWeb2; however, I no longer see recent snapshots since 2.4.2 release. Currently, I see `2.4.1.292.g7cdac4e-0.2017.10.10+1` packages but that's 2.4.1..?

**Comment by dnsmichi** [comment]
The release commit for 2.4.2 wasn't cherry-picked into master @lippserd 

@druchoo look at the build date, 10.10.2017 is fairly uptodate, especially when checking out the git commit.

```
michi@mbmif ~/coding/icinga/icingaweb2 (master=) $ git show 7cdac4e
commit 7cdac4eb9f909352b9b32d02b31c43126fb04b00
Merge: 6f37485c8 4b9a30755
Author: Alexander A. Klimov <alexander.klimov@icinga.com>
Date:   Mon Oct 9 14:41:30 2017 +0200

    Merge branch 'bugfix/setup-wizard-ldap-backend-wrong-default-type-3004'

    fixes #3004
```

**Comment by druchoo** [comment]
Ahh, i was searching for commit `g7cdac4e ` vs `7cdac4e ` and was also confused by `2.4.1`. Thanks for the clarification.

**Comment by lazyfrosch** [comment]
@dnsmichi you need to merge it, so the tag is part of master.

@lippserd please take care of this :)

**Comment by lazyfrosch** [comment]
We talked about this offline. Problem is:

1. We can't merge old branches to master - thats basically not a good idea supportwise in GIT
2. We have to make sure that the snapshot version is **older** than the next release (there is a version trick on Debian, but not RPM)

The correct way would be to pre-tag a new master, but the version would need to be something like `2.8.999` for RPM to work...
