### ISSUE TITLE
permission issue on /var/cache/icinga2 (debian jessie) upon restart

### ISSUE THREAD

**Issue by jeromedrouet** [Icinga/icinga-packaging#55]
Hi

there is a permission issue on directory /var/cache/icinga2/ preventing icinga classic ui from working : icinga 2.7.2-1 on debian jessie (issue appeared before 2.7 i don't recall the exact version) 
$ ls -alsd /var/cache/icinga2/
4 drwxr-x--- 2 nagios nagios 4096 nov.  13 17:32 /var/cache/icinga2/

permission for this directory are set (correctly : nagios:www-data) during install : 

$ grep cache /var/lib/dpkg/info/icinga2-common.postinst 
        setperm nagios www-data 0750 /var/cache/icinga2

but at each (re)start they are overridden (incorrectly : nagios:nagios) by prepare-dirs script called from icinga2.service unit : 
*******
$ grep -i cache /usr/lib/icinga2/prepare-dirs 
if [ -z "$ICINGA2_CACHE_DIR" ]; then
        ICINGA2_CACHE_DIR=$ICINGA2_STATE_DIR/cache/icinga2
mkdir -p $ICINGA2_CACHE_DIR
chown $ICINGA2_USER:$ICINGA2_GROUP $ICINGA2_CACHE_DIR
chmod 750 $ICINGA2_CACHE_DIR
******

so the classic-ui has not (www-data) permisisons to read status.dat from that directory.

One must manually do a "chgrp www-data /var/cache/icinga2/" after each (re)start

**Comment by lazyfrosch** [comment]
We decided to restrict permissions here, so the rest of the data store there is safe.

If you want to give access to there, please add the user accessing to the nagios/icinga group.

BTW. Classic UI has been removed with 2.8.0

**Comment by dgoetz** [comment]
Closing for no further feedback and the change and a workaround explained by lazyfrosch.
