### ISSUE TITLE
Add F27 and retire F25

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-packaging#57]
https://fedoramagazine.org/announcing-fedora-27/

**Comment by dgoetz** [comment]
Please remember there is one month overlap in which both are supported. So retiring F25 should be done on 14.12.2017.

**Comment by dnsmichi** [comment]
That's upstream, but not necessarily our schedule with release packages. I wouldn't bother here and only keep 2 Fedora's, especially for Jenkins jobs. The archive folder can be left intact for more months, why not.

**Comment by lazyfrosch** [comment]
F27 will be released with 2.8.0-2 soon

**Comment by lazyfrosch** [comment]
F27 builds are out. F25 builds will be removed from the buildsystem with the next Puppet run
