### ISSUE TITLE
Do not use /etc for systemd unit drop-ins

### ISSUE THREAD

**Issue by jkroepke** [Icinga/icinga-packaging#58]
Refer: https://github.com/Icinga/icinga2/pull/5612

According to the documentation, installed packages should only install unit files and other related files to /usr/lib/systemd/system or (/lib/systemd/system in Ubuntu/RHEL)

See: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Unit%20File%20Load%20Path

Instead using `/etc/systemd/system/icinga2.service.d` you should use `/lib/systemd/system/icinga2.service.d`.

Local administrators should use `/etc/systemd/system/icinga2.service.d` so the documentation must be not changed.

**Comment by lazyfrosch** [comment]
If the user decides to change the attributes there, and an RPM update won't override the change.

Idea was for the user to actually find the setting there...

**Comment by lazyfrosch** [comment]
Basically we decided to ship default-user settings, similar to `/etc/sysconfig`

Opinion @dgoetz - I would prefer not to change it now...

**Comment by lazyfrosch** [comment]
Oh, its not marked as `%config(noreplace)`.

Dang it.

**Comment by lazyfrosch** [comment]
First change: e54a7882efb34b345a3f5264711408af4705bc12

**Comment by lazyfrosch** [comment]
The next release will mark the drop-in as `%config(noreplace)` - so any user change will not be overridden.

We will keep the drop-in in /etc as it will be simpler for users to find and change it when needed.

**Comment by lazyfrosch** [comment]
Thanks for noticing use about your concerns :wink:
