### ISSUE TITLE
systemd limits.conf on SLES

### ISSUE THREAD

**Issue by Corbyn** [Icinga/icinga-packaging#61]
RPM installation of icinga2-2.8.0-1 on SLES 12 SP3 doesn't create directory /etc/systemd/system/icinga2.service.d
So limits.conf is not available and icinga2 is likely to crash because of the systemd TasksMax limit.

**Comment by lazyfrosch** [comment]
I was the solid opinion systemd on SLES 12.3 is older than that feature, apparently not.

**Comment by Corbyn** [comment]
Sometimes Suse is not that lazy... SLES 12 SP3 runs with systemd 228 :)

**Comment by lazyfrosch** [comment]
Lazy is not the word I was looking for :laughing: 

Testing with snapshots...

**Comment by lazyfrosch** [comment]
Fixed in snapshots, will be released with 2.8.0-2 for SLES
