### ISSUE TITLE
icinga2-studio for RHEL?

### ISSUE THREAD

**Issue by offsides** [Icinga/icinga-packaging#62]
I see that in the spec file the icinga2-studio package is only built for Fedora, not RHEL.  Is there a reason for that?  The EPEL repository provides the wxGTK3(-devel) packages, and while most RHEL servers don't run a GUI directly, running GUI apps via X11 forwarding is common.  Is there a fundamental reason why icinga2-studio is not available for RHEL?  Or was it jut assumed that it was only wanted/needed on Fedora?

Assuming there's no issues with building and running icinga2-studio on RHEL(7), can the spec be updated and an icinga2-studio package be provided for RHEL?

Thanks!

**Comment by dnsmichi** [comment]
Mostly because RHEL servers are generally running without any GUI (at least from my experience). 

icinga-studio hasn't been developed for a while now, so I wouldn't recommend starting to package it, if it gets removed at some point.

**Comment by offsides** [comment]
If it's deprecated, then not packaging it makes sense.  Thanks.

**Comment by dgoetz** [comment]
There was also another reason for me to not include it in the packages and this was the old version of xwidgets being not compatible.

**Comment by offsides** [comment]
Huh - RHEL 6/7 has version 3.0.2, F25 has 3.0.3, so I would have thought they would be compatible.  No worries, and thanks for the reply.
