### ISSUE TITLE
Renaming packages breaks the chef-icinga2 cookbook

### ISSUE THREAD

**Issue by schredder** [Icinga/icinga-packaging#63]
Some packages in the [centos 7 repo](http://packages.icinga.com/epel/7/release/noarch/) and [centos 6 repo](http://packages.icinga.com/epel/6/release/noarch/) have ".icinga" in their name, while others don't. And it looks as though the packages with ".icinga" in their name will eventually have it removed.

This makes it difficult to use the [chef-icinga2](https://github.com/Icinga/chef-icinga2) cookbook to pin a version of icinga2 and icingaweb2 because package installation will randomly start failing after the package suffix ([on which installation is dependent](https://github.com/Icinga/chef-icinga2/blob/v3.0.1/attributes/repo.rb#L20-L25)) changes.

**Comment by lazyfrosch** [comment]
Yes we updated the versioning with the current generation of our build server.

If you want to pin versions, please use proper repository snapshots as offered by tools like Pulp or Satellite.

What do you expect we should change for that? :smile:

**Comment by lazyfrosch** [comment]
As its not that easy to solve, and version pinning should be done on the repository side, I will close this issue.

Common methods are local mirrors and snapshots of packages to insure latest is pinned down for your site.

Our support is based on latest versions.
