### ISSUE TITLE
Windows: Missing VC Redist 2013 MSVCR120.dll

### ISSUE THREAD

**Issue by cxcv** [Icinga/icinga-packaging#64]
The current windows version lacks MSVCR120.dll, which was included in 2.7.x builds.

When I install Icinga2 from http://packages.icinga.com/windows/Icinga2-v2.8.0-x86_64.msi on a Windows Server 2016 (with latest patches), icinga2.exe raises "The program can't start because MSVCR120.dll is missing rom your computer. Try reinstalling the program to fix this problem." during start.

This file was distributed in the past and is missing in the sbin\ folder now. Though, looking at the binaries it seems that VCRedist 2017 is shipped. Are you mixing two compiler versions?

As a workaround: you can install the VCRedist form https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package , but it should be included.

Cheers
Benjamin

**Comment by lazyfrosch** [comment]
Could you have a look @Crunsher ?

**Comment by lazyfrosch** [comment]
@LordHepipud also noticed that.

**Comment by Crunsher** [comment]
With 2.8.0 we updated to msvc 14, so this is not the error I would expect :/

**Comment by tomlok** [comment]
Got the same error in Server 2008 R2 SP1 (patched and happy).

**Comment by LordHepipud** [comment]
Yes this is an issue. VCRedist 2013 is missing within the Agent Installer, causing the Agent to crash after an update to 2.8.0 on Sytems without the package beeing installed.

You will require this to work properly: https://support.microsoft.com/de-de/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package

**Comment by dnsmichi** [comment]
There's a ticket open on icinga2 itself, let's continue there (mainly docs).
