### ISSUE TITLE
Basic Auth and PHP-FPM

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icinga-packaging#71]
## Expected Behavior
Basic Auth to the Web2 API should work.

## Current Behavior
Returns a 401 Error

## Possible Solution
Because Basic auth is not done to the webserver, but to the PHP backend itself, it will fail in Apache httpd if 

```
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```

 is not set 

More Info:

https://devhacksandgoodies.wordpress.com/2014/06/27/apache-pass-authorization-header-to-phps-_serverhttp_authorization/

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.5.0
* Version used (`icinga2 --version`): 2.8.0
* Operating System and version: Centos 7 Latest

FYI: @lazyfrosch

**Comment by lazyfrosch** [comment]
I will defer this until the 2.5.1 release.

**Comment by lazyfrosch** [comment]
Thanks @SimonHoenscheid
