### ISSUE TITLE
icingaweb2 2.5.0 publish for centos6 failed

### ISSUE THREAD

**Issue by CLNRMN** [Icinga/icinga-packaging#72]
Hi, 

There is no RPM in the Repository because the publish for icingaweb2 2.5.0 centos6 failed (https://build.icinga.com/job/icingaweb2-release/).

Regards,
CLNRMN

**Comment by lippserd** [comment]
Hi,

Thanks for the report. There is a PR pending for this. Will be fixed asap.

Best regards,
Eric

**Comment by lazyfrosch** [comment]
Release has been published to the repository. thanks for informing us!
