### ISSUE TITLE
Incompatibility on debian stretch between icinga2 and monitoring-plugins-basic

### ISSUE THREAD

**Issue by Sauermann** [Icinga/icinga-packaging#74]
According to http://packages.icinga.com/debian/ problems with the packages should be repoprted here.

I use icinga2 on a Debian Stretch amd64 sytem and found an incompatibility between the following packages:

- [icinga2-common_2.8.0-1.stretch_all](http://packages.icinga.com/debian/pool/main/i/icinga2/) from packages.icinga.com
- [monitoring-plugins-basic 2.2-3](https://packages.debian.org/stretch/monitoring-plugins-basic) from packages.debian.org

The 'object CheckCommand "ssl" {' as defined in /usr/share/icinga2/include/command-plugins.conf introduces the -N attribute for SNI.
However the check_tcp command does not support the -N attribute and quits with a `/usr/lib/nagios/plugins/check_tcp: invalid option -- 'N'` message.

My current workaround is to comment out the respective lines in /usr/share/icinga2/include/command-plugins.conf

**Comment by mcktr** [comment]
Hi,

this is a known (and already fixed) issue .

Have a look here: icinga/icinga2#5775

**Comment by Sauermann** [comment]
Thanks for the reply.
