### ISSUE TITLE
Dependency problems when installing an older version of icinga2-ido-mysql RPM

### ISSUE THREAD

**Issue by vlk-charles** [Icinga/icinga-packaging#77]
When I try to install `icinga2` and `icinga2-ido-mysql` version `2.7.2-1.el7.icinga` in CentOS 7<sup>[1]</sup>:
`yum install icinga2{,-ido-mysql}-2.7.2-1.el7.icinga`
, yum fails and shows:
```
Error: Package: icinga2-bin-2.7.2-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: libcli.so.2.7.2()(64bit)
           Available: icinga2-libs-2.7.2-1.el7.icinga.x86_64 (icinga-stable-release)
               libcli.so.2.7.2()(64bit)
...
           Available: icinga2-libs-2.7.1-1.el7.icinga.x86_64 (icinga-stable-release)
              ~libcli.so.2.7.1()(64bit)
           Installing: icinga2-libs-2.8.0-1.el7.icinga.x86_64 (icinga-stable-release)
              ~libcli.so.2.8.0()(64bit)
```
and other similar messages. `yum` is trying to install `icinga2-libs` 2.8.0, which does not satisfy all the dependencies, instead of 2.7.2.

A workaround is to either install the packages separately:
`yum install icinga2-2.7.2-1.el7.icinga && yum install icinga2-ido-mysql-2.7.2-1.el7.icinga`
or to explicitly specify `icinga2-libs` too:
`yum install icinga2{,-{ido-mysql,libs}}-2.7.2-1.el7.icinga`

If I run the first command with `-v`, the problem is a little clearer:
```
icinga2-ido-mysql-2.7.2-1.el7.icinga.x86_64 requires: libyajl.so.2()(64bit)
--> Processing Dependency: libyajl.so.2()(64bit) for package: icinga2-ido-mysql-2.7.2-1.el7.icinga.x86_64
Searching pkgSack for dep: libyajl.so.2()(64bit)
TSINFO: Marking icinga2-libs-2.8.0-1.el7.icinga.x86_64 as install for icinga2-ido-mysql-2.7.2-1.el7.icinga.x86_64
icinga2-ido-mysql-2.7.2-1.el7.icinga.x86_64 requires: libremote.so.2.7.2()(64bit)
--> Processing Dependency: libremote.so.2.7.2()(64bit) for package: icinga2-ido-mysql-2.7.2-1.el7.icinga.x86_64
Searching pkgSack for dep: libremote.so.2.7.2()(64bit)
Potential resolving package icinga2-libs-2.7.2-1.el7.icinga.x86_64 has newer instance in ts.
```
The `libyajl.so.2` dependency, which is easier to satisfy, should probably be specified after all those more specific 2.7.2 dependencies.

<sup>[1]</sup> This is in a Docker container but that probably does not matter.

**Comment by dgoetz** [comment]
This is how yum handles dependencies. It searches for packages that satisfies dependencies, takes the latest version and tries then the same for them. So for getting a specific version it will always require an explicit installation of/update to it for all packages. There is nothing we could do about.

**Comment by vlk-charles** [comment]
But can you not repackage it so that it tries to satisfy `libremote.so.2.7.2` before it moves on to `libyajl.so.2`? Or maybe even better would be to make the `icinga2-ido-mysql` package depend on the `icinga2-libs` package itself, just like `icinga2-bin` does. I think this really is a packaging bug.

**Comment by dgoetz** [comment]
There is no ordering for requirements, so no to the first one. For the explicit dependency it is also against best practice to add explicit dependencies in addition to implicit ones created for rpmbuild, so while this is possible I am against it.
Furthermore the "problem" of having newer versions than the one wanted available is one of software management like Katello or Spacewalk and not one of packaging.
