### ISSUE TITLE
icinga2-classicui-config is missing version 2.8.0

### ISSUE THREAD

**Issue by sf-pc** [Icinga/icinga-packaging#78]
All `icinga2*` packages have a version 2.8.0, except the classicui package.

```
Error: Package: icinga2-classicui-config-2.7.2-1.el7.icinga.x86_64 (icinga-stable-release)
           Requires: icinga2 = 2.7.2-1.el7.icinga
           Removing: icinga2-2.6.3-1.el7.centos.x86_64 (@icinga-stable-release)
               icinga2 = 2.6.3-1.el7.centos
           Updated By: icinga2-2.8.0-1.el7.icinga.x86_64 (icinga-stable-release)
               icinga2 = 2.8.0-1.el7.icinga
````

**Comment by mcktr** [comment]
The package classicui-config and the configuration files have been removed in v2.8.0.

Have a look: 
https://www.icinga.com/2017/11/17/icinga-2-v2-8-0-released/
https://www.icinga.com/docs/icinga2/snapshot/doc/16-upgrading-icinga-2/#removed-classic-ui-config-package
