### ISSUE TITLE
Split sources for better management

### ISSUE THREAD

**Issue by Crunsher** [Icinga/icinga-packaging#80]
Having to care for and remember the 4 branches is extremely annoying and error prone.
We want to switch to a workflow using tags and PRs with merge commits for changed, master and next as the only branches.

**Comment by lazyfrosch** [comment]
Yes it is.

My current plan is to move each package and base type (rpm/deb) to it's own repo:

- rpm-icinga2
- deb-icinga2
- rpm-icingaweb2
- deb-icingaweb2

Comments on this?

**Comment by lazyfrosch** [comment]
This will be supported with https://github.com/Icinga/puppet-icinga_build/pull/49

And then sources from this repo will be migrated to separate repositories

**Comment by lazyfrosch** [comment]
A notice for @thardeck, RPM packaging will be moved to:
* https://github.com/Icinga/rpm-icinga2
* https://github.com/Icinga/rpm-icingaweb2

**Comment by lazyfrosch** [comment]
Migration is finished now, pending doc!
