### ISSUE TITLE
Windows Server 2008 R2 / 2012 R2 - api-ms-win-crt-runtime-I1-1-0.dll - missing

### ISSUE THREAD

**Issue by teclogi** [Icinga/icinga-packaging#81]
The following message is shown when I install the Icinga2-v2.8.0-x86_64.msi on a Windows Server 2012 R2 od Windows Server 2008 R2.
On a Windows Server 2016 the Installation is successful!

![image](https://user-images.githubusercontent.com/27726999/34213774-7d1132c0-e5a0-11e7-93ac-7cea28e75424.png)

**Comment by gunnarbeutner** [comment]
This will be fixed as part of the 2.8.1 release.
