### ISSUE TITLE
XML File for EPEL Repository has wrong paths included for icingabeat-5.6.6

### ISSUE THREAD

**Issue by pefmeister** [Icinga/icinga-packaging#82]
Hi there,

while syncing the Icinga EPEL repository for release 7 / x86_64 I got errors syncing icingabeat-5.6.6. I get the following error:

```
21:11:00 ERROR: Download failed: http://packages.icinga.com/epel/7/release/6-x86_64/icingabeat-5.6.6-x86_64.rpm - [Errno 14] HTTP Error 404 - Not Found.
```

The problem exists within the file http://packages.icinga.com/epel/7/release/repodata/020ae5cad81623c4bf16332786f2772c7e55b08e-primary.xml.gz

The following lines are errornous:

```
<location href="6-i686/icingabeat-5.6.6-i686.rpm"/>
<location href="6-x86_64/icingabeat-5.6.6-x86_64.rpm"/>
```

They should look like this:

```
<location href="i686/icingabeat-5.6.6-i686.rpm"/>
<location href="x86_64/icingabeat-5.6.6-x86_64.rpm"/>
```

I hope this issue is correctly placed :-)

Thanks
Stephan

**Comment by lazyfrosch** [comment]
@bobapple same problem as on SLES?

**Comment by bobapple** [comment]
Yes, it's the same issue as #83

@pefmeister it should be fixed now. Please let us know if you still have problems with the repo
