### ISSUE TITLE
Broken Icinga2 SLES repository

### ISSUE THREAD

**Issue by paddg** [Icinga/icinga-packaging#83]
The metadata (repodata) of http://packages.icinga.com/SUSE/sles12-sp3/release/ seems not to be in sync with the content of the repository. This is the error I get if I try to mirror it with Suse Manager (SMT):
```
E ‘http://packages.icinga.com/SUSE/sles12-sp3/release/6-i686/icingabeat-5.6.6-i686.rpm’: 404 Not Found
E ‘http://packages.icinga.com/SUSE/sles12-sp3/release/6-x86_64/icingabeat-5.6.6-x86_64.rpm’: 404 Not Found
```

**Comment by lazyfrosch** [comment]
@bobapple please have a look :)

**Comment by bobapple** [comment]
I re-generated the metadata and it should be fine now. 
@paddg can you verify if it's working correctly now?

**Comment by paddg** [comment]
Thank you very much @bobapple and @lazyfrosch! Now it works.
