### ISSUE TITLE
Debian/Ubuntu: make Icinga Web 2 working OOTB

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icinga-packaging#84]
As a sysadmin I have to do [this](https://github.com/Al2Klimov/graphite-web-div0/commit/7d566cc968a194164564ba70b277768c83385c15) to make IW2 working. Please fix that here and (if possible) in the distros.

**Comment by Al2Klimov** [comment]
As discussed w/ @lazyfrosch (offline):

> You could also use IW2 w/ mod_php so we can't just do as you suggest.

@lazyfrosch Could we do that only if mod_php is disabled/absent?

**Comment by lazyfrosch** [comment]
Problem that on Ubuntu PHP FPM is the default implementation installed when installing Icinga Web 2.

On Debian this is still mod_php, which gets enabled by default.

So the real problem is here that Ubuntu does install, but not activate the FPM/Proxy modules in Apache by default. This is sadly nothing we can easily fix...

I will verify this, and possibly add the info to Icinga Web's documentation...

**Comment by Al2Klimov** [comment]
1. "Problem"? I've been told PHP FPM is an improvement over mod_php.
2. "nothing we can easily fix" – Don't debs have post install scripts we could [use](https://github.com/Icinga/icinga-packaging/issues/84#issuecomment-355938701)?

**Comment by lazyfrosch** [comment]
Theoretically yes, but it is not recommended to interfere with other packages.

E.g. what if the user wants to disable FPM, even when it is installed? Should we re-enable it on every update of Icinga Web? Maybe just on initial installation would be fine...

**Comment by Al2Klimov** [comment]
> Maybe just on initial installation would be fine...

Confirmed.

**Comment by davidolrik** [comment]
Or maybe create 2 icingaweb2 packages:

- `icingaweb2-fpm`
- `icingaweb2-libapache`

and a meta packages `icingaweb2` that depends on either and "provides" "icingaweb2" for others to depend on.

With this I would `apt install icingaweb2-fpm` and never even get apache installed.

**Comment by Al2Klimov** [comment]
I think I've [fixed this](https://github.com/Icinga/icingaweb2/commit/06802cb94e4528ef0e92352b6fe5581aefc5b702).

@lazyfrosch Any chance we can make my doc change the default behavior of our packages – if someone just installs icingaweb2 on Ubuntu?

**Comment by dnsmichi** [comment]
I don't think we should move away from PHP FPM which is the default on RHEL/SLES distributions. The goal is to focus on just one configuration method and push support for it.
