### ISSUE TITLE
Update RPM/Debian packaging stuff for new libraries

### ISSUE THREAD

**Issue by gunnarbeutner** [Icinga/icinga-packaging#86]
1. libbase, libconfig, don't exist anymore (at least not as installable shared libraries).
2. There are two new libraries for DB IDO: libmysql_shim and libpgsql_shim.

**Comment by gunnarbeutner** [comment]
@lazyfrosch: Can you please have a look at this?

**Comment by rahonalab** [comment]
Issue with icinga2-bin: /usr/lib/nagios/plugins/check_nscp_api
Probably related: 
check_nscp_api is linked to libremote.so.2.8.0 not libremote.so.2.8.1

/usr/lib/nagios/plugins/check_nscp_api: error while loading shared libraries: libremote.so.2.8.0: cannot open shared object file: No such file or directory

libicinga2: /usr/lib/x86_64-linux-gnu/icinga2/libremote.so.2.8.1

**Comment by gunnarbeutner** [comment]
@rahonalab: That appears to be unrelated to this issue.

**Comment by lazyfrosch** [comment]
Current changes look fine for me!
