### ISSUE TITLE
Support non-SCL versions of PHP

### ISSUE THREAD

**Issue by miken32** [Icinga/icinga-packaging#89]
@dnsmichi asked in [issue 69](https://github.com/Icinga/icinga-packaging/issues/69#issuecomment-347845032)
>Do you know a possible way of RPM supporting either one package dependency or the other?

But the issue was closed and locked so I can't comment there. RPM does support this as long as you're using a fairly new version of rpm (>= 4.13.) You can provide a line like this, for example:

    Requires: (rh-php70-php-common >= 5.6.0 or php-common >= 5.6.0)

However it's quite disingenuous to say that PHP >= 5.6 is required but then look specifically for rh-php70-*. Something like this might be better:

    Requires: (rh-php56 or rh-php70 or rh-php71 or php-common >= 5.6.0)

See [here](http://rpm.org/user_doc/boolean_dependencies.html) for details.

And let me echo the complaints of other users. This was a poor move; as a user of and contributor to this project, I'm not happy with it at all.

**Comment by dnsmichi** [comment]
Thanks.

> There is no need to start with the blaming tone again. This does not help at all.

https://github.com/Icinga/icinga-packaging/issues/69#issuecomment-357249172 tells about the next step, this is a duplicate.
